In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from IPython.display import display, HTML
# Set the format for floating point numbers to show no decimal places
pd.set_option('display.float_format', lambda x: '%.0f' % x)
# To display plots inline within the notebook
%matplotlib inline
# Set the notebook width to 100%

In [2]:
numericFacts   = pd.read_csv('/kaggle/input/datasets/sajamoussa/2026m2/num.tsv', sep='\t', low_memory=False, keep_default_na=False)
submissions  = pd.read_csv('/kaggle/input/datasets/sajamoussa/2026m2/sub.tsv', sep='\t', low_memory=False, keep_default_na=False)
tags  = pd.read_csv('/kaggle/input/datasets/sajamoussa/2026m2/tag.tsv', sep='\t', low_memory=False, keep_default_na=False)
print('Sum of Filings:', str(len(numericFacts) + len(submissions) + len(tags)))

Sum of Filings: 5500389

In [3]:
submissions

,adsh,cik,name,sic,countryba,stprba,cityba,zipba,bas1,bas2,...,accepted,prevrpt,detail,instance,nciks,aciks,pubfloatusd,floatdate,floataxis,floatmems
0,0000002488-26-000014,2488,ADVANCED MICRO DEVICES INC,3674,US,CA,SANTA CLARA,95054,2485 AUGUSTINE DRIVE,,...,2026-02-03 16:16:00.0,0,0,amd-20260203_htm.xml,1,,,,,
1,0000002488-26-000018,2488,ADVANCED MICRO DEVICES INC,3674,US,CA,SANTA CLARA,95054,2485 AUGUSTINE DRIVE,,...,2026-02-03 18:15:00.0,0,1,amd-20251227_htm.xml,1,,232300000000.00,20240630,,1
2,0000002488-26-000021,2488,ADVANCED MICRO DEVICES INC,3674,US,CA,SANTA CLARA,95054,2485 AUGUSTINE DRIVE,,...,2026-02-04 15:07:00.0,0,0,amd-20251227_htm.xml,1,,232300000000.00,20240630,,1
3,0000003545-26-000010,3545,"ALICO, INC.",0100,US,FL,"FT. MYERS,",33913,10070 DANIELS INTERSTATE COURT STE. 100,,...,2026-02-04 16:03:00.0,0,0,alco-20260204_htm.xml,1,,,,,
4,0000003545-26-000012,3545,"ALICO, INC.",0100,US,FL,"FT. MYERS,",33913,10070 DANIELS INTERSTATE COURT STE. 100,,...,2026-02-04 16:43:00.0,0,1,alco-20251231_htm.xml,1,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8751,0002074176-26-000005,2074176,"VIPER ENERGY, INC.",1311,US,TX,MIDLAND,79701,500 WEST TEXAS AVE.,SUITE 100,...,2026-02-23 16:03:00.0,0,0,vnom-20260223_htm.xml,1,,,,,
8752,0002074176-26-000010,2074176,"VIPER ENERGY, INC.",1311,US,TX,MIDLAND,79701,500 WEST TEXAS AVE.,SUITE 100,...,2026-02-25 16:07:00.0,0,1,vnom-20251231_htm.xml,1,,5000000000.00,20250630,,1
8753,0002082557-26-000013,2082557,GOLUB CAPITAL PRIVATE INCOME FUND S,,US,DE,WILMINGTON,19801,1209 ORANGE STREET,,...,2026-02-24 17:08:00.0,0,0,gpifs-20260223_htm.xml,1,,,,,
8754,0002082559-26-000018,2082559,GOLUB CAPITAL PRIVATE INCOME FUND I,,US,DE,WILMINGTON,19801,1209 ORANGE STREET,,...,2026-02-24 17:06:00.0,0,0,gpifi-20260223_htm.xml,1,,,,,
8755,0002089661-26-000016,2089661,SUNOCOCORP LLC,2911,US,TX,DALLAS,75225,8111 WESTCHESTER DRIVE,SUITE 400,...,2026-02-19 16:29:00.0,0,1,sunc-20251231_htm.xml,1,,0.00,20250630,,1

In [4]:
submissions.columns

Index(['adsh', 'cik', 'name', 'sic', 'countryba', 'stprba', 'cityba', 'zipba',
       'bas1', 'bas2', 'baph', 'countryma', 'stprma', 'cityma', 'zipma',
       'mas1', 'mas2', 'countryinc', 'stprinc', 'ein', 'former', 'changed',
       'afs', 'wksi', 'fye', 'form', 'period', 'fy', 'fp', 'filed', 'accepted',
       'prevrpt', 'detail', 'instance', 'nciks', 'aciks', 'pubfloatusd',
       'floatdate', 'floataxis', 'floatmems'],
      dtype='object')

In [5]:
submissions.drop(columns=['countryba', 'stprba', 'cityba', 'zipba',
       'bas1', 'bas2', 'baph', 'countryma', 'stprma', 'cityma', 'zipma',
       'mas1', 'mas2', 'countryinc', 'stprinc', 'ein', 'former', 'changed',
       'afs', 'wksi', 'fye', 'period', 'fy', 'fp', 'filed', 'accepted',
       'prevrpt', 'detail', 'instance', 'nciks', 'aciks', 'pubfloatusd',
       'floatdate', 'floataxis', 'floatmems'], inplace=True)

In [6]:
submissions.columns

Index(['adsh', 'cik', 'name', 'sic', 'form'], dtype='object')

In [7]:
submissions.head()

                   adsh   cik                        name   sic    form
0  0000002488-26-000014  2488  ADVANCED MICRO DEVICES INC  3674     8-K
1  0000002488-26-000018  2488  ADVANCED MICRO DEVICES INC  3674    10-K
2  0000002488-26-000021  2488  ADVANCED MICRO DEVICES INC  3674  10-K/A
3  0000003545-26-000010  3545                 ALICO, INC.  0100     8-K
4  0000003545-26-000012  3545                 ALICO, INC.  0100    10-Q

In [8]:
Annualsubmissions = submissions[
    submissions['form'] == '10-K'
]

In [9]:
submissions.head()

                   adsh   cik                        name   sic    form
0  0000002488-26-000014  2488  ADVANCED MICRO DEVICES INC  3674     8-K
1  0000002488-26-000018  2488  ADVANCED MICRO DEVICES INC  3674    10-K
2  0000002488-26-000021  2488  ADVANCED MICRO DEVICES INC  3674  10-K/A
3  0000003545-26-000010  3545                 ALICO, INC.  0100     8-K
4  0000003545-26-000012  3545                 ALICO, INC.  0100    10-Q

In [10]:
numericFacts

,adsh,tag,version,ddate,qtrs,uom,dimh,iprx,value,footnote,footlen,dimn,coreg,durp,datp,dcml
0,0000002488-26-000018,AccountsPayableCurrent,us-gaap/2025,20241231,0,USD,0x00000000,0,2466000000.0000,,0,0,,0,3,-6
1,0000002488-26-000018,AccountsPayableCurrent,us-gaap/2025,20251231,0,USD,0x00000000,0,2929000000.0000,,0,0,,0,4,-6
2,0000002488-26-000018,AccountsPayableCurrentAndNoncurrent,us-gaap/2025,20241231,0,USD,0xad66b56c81571b0e9d4882f564c06174,0,476000000.0000,,0,2,,0,3,-6
3,0000002488-26-000018,AccountsPayableCurrentAndNoncurrent,us-gaap/2025,20251231,0,USD,0xad66b56c81571b0e9d4882f564c06174,0,408000000.0000,,0,2,,0,4,-6
4,0000002488-26-000018,AccountsReceivableNetCurrent,us-gaap/2025,20241231,0,USD,0x00000000,0,6192000000.0000,,0,0,,0,3,-6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4990814,0002089661-26-000016,VariableLeaseCost,us-gaap/2025,20251231,4,USD,0x00000000,0,11000000.0000,,0,0,,0,0,-6
4990815,0002089661-26-000016,WeightedAverageNumberOfDilutedSharesOutstanding,us-gaap/2025,20251231,4,shares,0x00000000,0,51517198.0000,,0,0,,0,0,0
4990816,0002089661-26-000016,WeightedAverageNumberOfDilutedSharesOutstanding,us-gaap/2025,20251231,4,shares,0x00000000,1,51517198.0000,,0,0,,0,0,0
4990817,0002089661-26-000016,WeightedAverageNumberOfSharesOutstandingBasic,us-gaap/2025,20251231,4,shares,0x00000000,0,51517198.0000,,0,0,,0,0,0
4990818,0002089661-26-000016,WeightedAverageNumberOfSharesOutstandingBasic,us-gaap/2025,20251231,4,shares,0x00000000,1,51517198.0000,,0,0,,0,0,0

In [11]:
numericFacts

,adsh,tag,version,ddate,qtrs,uom,dimh,iprx,value,footnote,footlen,dimn,coreg,durp,datp,dcml
0,0000002488-26-000018,AccountsPayableCurrent,us-gaap/2025,20241231,0,USD,0x00000000,0,2466000000.0000,,0,0,,0,3,-6
1,0000002488-26-000018,AccountsPayableCurrent,us-gaap/2025,20251231,0,USD,0x00000000,0,2929000000.0000,,0,0,,0,4,-6
2,0000002488-26-000018,AccountsPayableCurrentAndNoncurrent,us-gaap/2025,20241231,0,USD,0xad66b56c81571b0e9d4882f564c06174,0,476000000.0000,,0,2,,0,3,-6
3,0000002488-26-000018,AccountsPayableCurrentAndNoncurrent,us-gaap/2025,20251231,0,USD,0xad66b56c81571b0e9d4882f564c06174,0,408000000.0000,,0,2,,0,4,-6
4,0000002488-26-000018,AccountsReceivableNetCurrent,us-gaap/2025,20241231,0,USD,0x00000000,0,6192000000.0000,,0,0,,0,3,-6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4990814,0002089661-26-000016,VariableLeaseCost,us-gaap/2025,20251231,4,USD,0x00000000,0,11000000.0000,,0,0,,0,0,-6
4990815,0002089661-26-000016,WeightedAverageNumberOfDilutedSharesOutstanding,us-gaap/2025,20251231,4,shares,0x00000000,0,51517198.0000,,0,0,,0,0,0
4990816,0002089661-26-000016,WeightedAverageNumberOfDilutedSharesOutstanding,us-gaap/2025,20251231,4,shares,0x00000000,1,51517198.0000,,0,0,,0,0,0
4990817,0002089661-26-000016,WeightedAverageNumberOfSharesOutstandingBasic,us-gaap/2025,20251231,4,shares,0x00000000,0,51517198.0000,,0,0,,0,0,0
4990818,0002089661-26-000016,WeightedAverageNumberOfSharesOutstandingBasic,us-gaap/2025,20251231,4,shares,0x00000000,1,51517198.0000,,0,0,,0,0,0

In [12]:
numericFacts.columns

Index(['adsh', 'tag', 'version', 'ddate', 'qtrs', 'uom', 'dimh', 'iprx',
       'value', 'footnote', 'footlen', 'dimn', 'coreg', 'durp', 'datp',
       'dcml'],
      dtype='object')

In [13]:
numericFacts.drop(columns=['version', 'uom', 'dimh', 'iprx', 'footlen', 'dimn', 'coreg', 'durp', 'datp',
       'dcml'], inplace=True)

In [14]:
numericFacts.head()

,adsh,tag,ddate,qtrs,value,footnote
0,0000002488-26-000018,AccountsPayableCurrent,20241231,0,2466000000.0000,
1,0000002488-26-000018,AccountsPayableCurrent,20251231,0,2929000000.0000,
2,0000002488-26-000018,AccountsPayableCurrentAndNoncurrent,20241231,0,476000000.0000,
3,0000002488-26-000018,AccountsPayableCurrentAndNoncurrent,20251231,0,408000000.0000,
4,0000002488-26-000018,AccountsReceivableNetCurrent,20241231,0,6192000000.0000,

In [15]:
tags

,tag,version,custom,abstract,datatype,iord,crdr,tlabel,doc
0,A.5000EuroDenominatedNotesDue2033Member,0000059478-26-000013,1,1,member,,,.5000% Euro Denominated Notes Due 2033 [Member],.5000% Euro Denominated Notes Due 2033
1,A.B.BrownFacilityMember,0001130310-26-000008,1,1,member,,,A.B. Brown Facility [Member],A.B. Brown Facility
2,A.C.SolucoesParaPiscinasLda.Member,0001193125-26-074833,1,1,member,,,"A.C. Solucoes para Piscinas, Lda. [Member]","A.C. Solucoes para Piscinas, Lda."
3,A.Member,0000909327-26-000022,1,1,member,,,A-. [Member],A-.
4,A.PacificMember,0001628280-26-010047,1,1,member,,,A. Pacific [Member],A component of an entity for which there is an...
...,...,...,...,...,...,...,...,...,...
500809,ZZ524292,naics/2025,0,1,member,,,524292 Pharmacy Benefit Management and Other T...,Third Party Administration of Insurance and Pe...
500810,ZZ525110,naics/2025,0,1,member,,,525110 Pension Funds [Member],Pension Funds
500811,ZZ541214,naics/2025,0,1,member,,,541214 Payroll Services [Member],Payroll Services
500812,ZZ541990,naics/2025,0,1,member,,,"541990 All Other Professional, Scientific, and...","All Other Professional, Scientific, and Techni..."
500813,ZZ811412,naics/2025,0,1,member,,,811412 Appliance Repair and Maintenance [Member],Appliance Repair and Maintenance

In [16]:
Texts   = pd.read_csv('/kaggle/input/datasets/sajamoussa/2026m2/txt.tsv', sep='\t', low_memory=False, keep_default_na=False)

In [17]:
Texts

,adsh,tag,version,ddate,qtrs,iprx,lang,dcml,durp,datp,dimh,dimn,coreg,escaped,srclen,txtlen,footnote,footlen,context,value
0,0000002488-26-000014,AmendmentFlag,dei/2025,20260131,0,0,en-US,32767,0,-3,0x00000000,0,,0,5,5,,0,c-1,false
1,0000002488-26-000014,CityAreaCode,dei/2025,20260131,0,0,en-US,32767,0,-3,0x00000000,0,,0,3,3,,0,c-1,408
2,0000002488-26-000014,DocumentPeriodEndDate,dei/2025,20260131,0,0,en-US,32767,0,-3,0x00000000,0,,0,10,10,,0,c-1,2026-02-03
3,0000002488-26-000014,DocumentType,dei/2025,20260131,0,0,en-US,32767,0,-3,0x00000000,0,,0,3,3,,0,c-1,8-K
4,0000002488-26-000014,EntityAddressAddressLine1,dei/2025,20260131,0,0,en-US,32767,0,-3,0x00000000,0,,0,20,20,,0,c-1,2485 Augustine Drive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
687998,0002089661-26-000016,TradeAndOtherAccountsReceivablePolicy,us-gaap/2025,20251231,4,0,en-US,32767,0,0,0x00000000,0,,1,1684,896,,0,c-1,Accounts Receivable The majority of trade rece...
687999,0002089661-26-000016,TradingSymbol,dei/2025,20251231,4,0,en-US,32767,0,0,0x00000000,0,,0,4,4,,0,c-1,SUNC
688000,0002089661-26-000016,UnitsOfPartnershipInterestDescription,us-gaap/2025,20251231,4,0,en-US,32767,0,0,0x538bb07b489471c3195a4431bcd95bd4,1,,0,1665,1665,,0,c-475,Class C Units (i) are not convertible or excha...
688001,0002089661-26-000016,UnitsOfPartnershipInterestDescription,us-gaap/2025,20251231,4,0,en-US,32767,0,0,0x62ab6d8bd130346f3744814dcb38998b,1,,0,918,918,,0,c-478,Class D Units (i) except as required by law an...
688002,0002089661-26-000016,UseOfEstimates,us-gaap/2025,20251231,4,0,en-US,32767,0,0,0x00000000,0,,1,907,497,,0,c-1,Use of Estimates The preparation of consolidat...

In [18]:
Texts.columns

Index(['adsh', 'tag', 'version', 'ddate', 'qtrs', 'iprx', 'lang', 'dcml',
       'durp', 'datp', 'dimh', 'dimn', 'coreg', 'escaped', 'srclen', 'txtlen',
       'footnote', 'footlen', 'context', 'value'],
      dtype='object')

In [19]:
Texts.drop(columns=[ 'iprx', 'lang', 'dcml',
       'durp', 'datp', 'dimh', 'dimn', 'coreg', 'escaped', 'srclen', 'txtlen',
        'footlen', 'context'], inplace=True)

In [20]:
Texts.head()

,adsh,tag,version,ddate,qtrs,footnote,value
0,0000002488-26-000014,AmendmentFlag,dei/2025,20260131,0,,false
1,0000002488-26-000014,CityAreaCode,dei/2025,20260131,0,,408
2,0000002488-26-000014,DocumentPeriodEndDate,dei/2025,20260131,0,,2026-02-03
3,0000002488-26-000014,DocumentType,dei/2025,20260131,0,,8-K
4,0000002488-26-000014,EntityAddressAddressLine1,dei/2025,20260131,0,,2485 Augustine Drive

In [21]:
joinedFactsAndSubmissions = numericFacts.join(submissions.set_index('adsh'), on = 'adsh')

In [22]:
joinedFactsAndSubmissions

,adsh,tag,ddate,qtrs,value,footnote,cik,name,sic,form
0,0000002488-26-000018,AccountsPayableCurrent,20241231,0,2466000000.0000,,2488,ADVANCED MICRO DEVICES INC,3674,10-K
1,0000002488-26-000018,AccountsPayableCurrent,20251231,0,2929000000.0000,,2488,ADVANCED MICRO DEVICES INC,3674,10-K
2,0000002488-26-000018,AccountsPayableCurrentAndNoncurrent,20241231,0,476000000.0000,,2488,ADVANCED MICRO DEVICES INC,3674,10-K
3,0000002488-26-000018,AccountsPayableCurrentAndNoncurrent,20251231,0,408000000.0000,,2488,ADVANCED MICRO DEVICES INC,3674,10-K
4,0000002488-26-000018,AccountsReceivableNetCurrent,20241231,0,6192000000.0000,,2488,ADVANCED MICRO DEVICES INC,3674,10-K
...,...,...,...,...,...,...,...,...,...,...
4990814,0002089661-26-000016,VariableLeaseCost,20251231,4,11000000.0000,,2089661,SUNOCOCORP LLC,2911,10-K
4990815,0002089661-26-000016,WeightedAverageNumberOfDilutedSharesOutstanding,20251231,4,51517198.0000,,2089661,SUNOCOCORP LLC,2911,10-K
4990816,0002089661-26-000016,WeightedAverageNumberOfDilutedSharesOutstanding,20251231,4,51517198.0000,,2089661,SUNOCOCORP LLC,2911,10-K
4990817,0002089661-26-000016,WeightedAverageNumberOfSharesOutstandingBasic,20251231,4,51517198.0000,,2089661,SUNOCOCORP LLC,2911,10-K
4990818,0002089661-26-000016,WeightedAverageNumberOfSharesOutstandingBasic,20251231,4,51517198.0000,,2089661,SUNOCOCORP LLC,2911,10-K

In [23]:
annual_forms = ['10-K', '20-F', '40-F']  

joinedFactsAndSubmissionsAnnual = joinedFactsAndSubmissions[
    (joinedFactsAndSubmissions['form'].isin(annual_forms))
]
joinedFactsAndSubmissionsAnnual

,adsh,tag,ddate,qtrs,value,footnote,cik,name,sic,form
0,0000002488-26-000018,AccountsPayableCurrent,20241231,0,2466000000.0000,,2488,ADVANCED MICRO DEVICES INC,3674,10-K
1,0000002488-26-000018,AccountsPayableCurrent,20251231,0,2929000000.0000,,2488,ADVANCED MICRO DEVICES INC,3674,10-K
2,0000002488-26-000018,AccountsPayableCurrentAndNoncurrent,20241231,0,476000000.0000,,2488,ADVANCED MICRO DEVICES INC,3674,10-K
3,0000002488-26-000018,AccountsPayableCurrentAndNoncurrent,20251231,0,408000000.0000,,2488,ADVANCED MICRO DEVICES INC,3674,10-K
4,0000002488-26-000018,AccountsReceivableNetCurrent,20241231,0,6192000000.0000,,2488,ADVANCED MICRO DEVICES INC,3674,10-K
...,...,...,...,...,...,...,...,...,...,...
4990814,0002089661-26-000016,VariableLeaseCost,20251231,4,11000000.0000,,2089661,SUNOCOCORP LLC,2911,10-K
4990815,0002089661-26-000016,WeightedAverageNumberOfDilutedSharesOutstanding,20251231,4,51517198.0000,,2089661,SUNOCOCORP LLC,2911,10-K
4990816,0002089661-26-000016,WeightedAverageNumberOfDilutedSharesOutstanding,20251231,4,51517198.0000,,2089661,SUNOCOCORP LLC,2911,10-K
4990817,0002089661-26-000016,WeightedAverageNumberOfSharesOutstandingBasic,20251231,4,51517198.0000,,2089661,SUNOCOCORP LLC,2911,10-K
4990818,0002089661-26-000016,WeightedAverageNumberOfSharesOutstandingBasic,20251231,4,51517198.0000,,2089661,SUNOCOCORP LLC,2911,10-K

In [24]:
joinedTextAndSubmissions = Texts.join(submissions.set_index('adsh'), on = 'adsh')

In [25]:
joinedTextAndSubmissions

,adsh,tag,version,ddate,qtrs,footnote,value,cik,name,sic,form
0,0000002488-26-000014,AmendmentFlag,dei/2025,20260131,0,,false,2488,ADVANCED MICRO DEVICES INC,3674,8-K
1,0000002488-26-000014,CityAreaCode,dei/2025,20260131,0,,408,2488,ADVANCED MICRO DEVICES INC,3674,8-K
2,0000002488-26-000014,DocumentPeriodEndDate,dei/2025,20260131,0,,2026-02-03,2488,ADVANCED MICRO DEVICES INC,3674,8-K
3,0000002488-26-000014,DocumentType,dei/2025,20260131,0,,8-K,2488,ADVANCED MICRO DEVICES INC,3674,8-K
4,0000002488-26-000014,EntityAddressAddressLine1,dei/2025,20260131,0,,2485 Augustine Drive,2488,ADVANCED MICRO DEVICES INC,3674,8-K
...,...,...,...,...,...,...,...,...,...,...,...
687998,0002089661-26-000016,TradeAndOtherAccountsReceivablePolicy,us-gaap/2025,20251231,4,,Accounts Receivable The majority of trade rece...,2089661,SUNOCOCORP LLC,2911,10-K
687999,0002089661-26-000016,TradingSymbol,dei/2025,20251231,4,,SUNC,2089661,SUNOCOCORP LLC,2911,10-K
688000,0002089661-26-000016,UnitsOfPartnershipInterestDescription,us-gaap/2025,20251231,4,,Class C Units (i) are not convertible or excha...,2089661,SUNOCOCORP LLC,2911,10-K
688001,0002089661-26-000016,UnitsOfPartnershipInterestDescription,us-gaap/2025,20251231,4,,Class D Units (i) except as required by law an...,2089661,SUNOCOCORP LLC,2911,10-K
688002,0002089661-26-000016,UseOfEstimates,us-gaap/2025,20251231,4,,Use of Estimates The preparation of consolidat...,2089661,SUNOCOCORP LLC,2911,10-K

In [26]:
annual_forms = ['10-K', '20-F', '40-F']  

joinedTextAndSubmissionsAnnual = joinedTextAndSubmissions[
    (joinedTextAndSubmissions['form'].isin(annual_forms))
]
joinedTextAndSubmissionsAnnual

,adsh,tag,version,ddate,qtrs,footnote,value,cik,name,sic,form
22,0000002488-26-000018,AdvertisingCostsPolicyTextBlock,us-gaap/2025,20251231,4,,Marketing and Advertising Expenses Advertising...,2488,ADVANCED MICRO DEVICES INC,3674,10-K
23,0000002488-26-000018,AmendmentFlag,dei/2025,20251231,4,,false,2488,ADVANCED MICRO DEVICES INC,3674,10-K
24,0000002488-26-000018,AuditorFirmId,dei/2025,20251231,4,,42,2488,ADVANCED MICRO DEVICES INC,3674,10-K
25,0000002488-26-000018,AuditorLocation,dei/2025,20251231,4,,"San Jose, California",2488,ADVANCED MICRO DEVICES INC,3674,10-K
26,0000002488-26-000018,AuditorName,dei/2025,20251231,4,,Ernst& Young LLP,2488,ADVANCED MICRO DEVICES INC,3674,10-K
...,...,...,...,...,...,...,...,...,...,...,...
687998,0002089661-26-000016,TradeAndOtherAccountsReceivablePolicy,us-gaap/2025,20251231,4,,Accounts Receivable The majority of trade rece...,2089661,SUNOCOCORP LLC,2911,10-K
687999,0002089661-26-000016,TradingSymbol,dei/2025,20251231,4,,SUNC,2089661,SUNOCOCORP LLC,2911,10-K
688000,0002089661-26-000016,UnitsOfPartnershipInterestDescription,us-gaap/2025,20251231,4,,Class C Units (i) are not convertible or excha...,2089661,SUNOCOCORP LLC,2911,10-K
688001,0002089661-26-000016,UnitsOfPartnershipInterestDescription,us-gaap/2025,20251231,4,,Class D Units (i) except as required by law an...,2089661,SUNOCOCORP LLC,2911,10-K
688002,0002089661-26-000016,UseOfEstimates,us-gaap/2025,20251231,4,,Use of Estimates The preparation of consolidat...,2089661,SUNOCOCORP LLC,2911,10-K

In [27]:
unique_sic = submissions['sic'].unique()
print(f"Count: {len(unique_sic)}")

Count: 366

In [28]:
joinedTextAndSubmissions1311 = joinedTextAndSubmissionsAnnual[
    (joinedTextAndSubmissionsAnnual['sic'] == '1311')
]
joinedFactsAndSubmissions1311 = joinedFactsAndSubmissionsAnnual[
    (joinedFactsAndSubmissionsAnnual['sic'] == '1311') ]

In [29]:
joinedTextAndSubmissions1311

,adsh,tag,version,ddate,qtrs,footnote,value,cik,name,sic,form
12672,0000033213-26-000018,AmendmentFlag,dei/2025,20251231,4,,false,33213,EQT CORP,1311,10-K
12673,0000033213-26-000018,AssetRetirementObligationsAndEnvironmentalCost...,us-gaap/2025,20251231,4,,Asset Retirement Obligations. The Company accr...,33213,EQT CORP,1311,10-K
12674,0000033213-26-000018,AssetsAndLiabilitiesLesseeTableTextBlock,0000033213-26-000018,20251231,4,,The following table summarizes the Company's r...,33213,EQT CORP,1311,10-K
12675,0000033213-26-000018,AuditorFirmId,dei/2025,20251231,4,,42,33213,EQT CORP,1311,10-K
12676,0000033213-26-000018,AuditorLocation,dei/2025,20251231,4,,"Pittsburgh, Pennsylvania",33213,EQT CORP,1311,10-K
...,...,...,...,...,...,...,...,...,...,...,...
687459,0002074176-26-000010,SubsequentEventsTextBlock,us-gaap/2025,20251231,4,,SUBSEQUENT EVENTS Cash Dividend On February 18...,2074176,"VIPER ENERGY, INC.",1311,10-K
687460,0002074176-26-000010,TaxJurisdictionOfDomicileExtensibleEnumeration,us-gaap/2025,20251231,4,,http://xbrl.sec.gov/country/2025#US,2074176,"VIPER ENERGY, INC.",1311,10-K
687461,0002074176-26-000010,TradeAndOtherAccountsReceivablePolicy,us-gaap/2025,20251231,4,,Royalty Income Receivable Royalty income recei...,2074176,"VIPER ENERGY, INC.",1311,10-K
687462,0002074176-26-000010,TradingSymbol,dei/2025,20251231,4,,VNOM,2074176,"VIPER ENERGY, INC.",1311,10-K
687463,0002074176-26-000010,UseOfEstimates,us-gaap/2025,20251231,4,,Use of Estimates Certain amounts included in o...,2074176,"VIPER ENERGY, INC.",1311,10-K

In [30]:
joinedFactsAndSubmissions1311

,adsh,tag,ddate,qtrs,value,footnote,cik,name,sic,form
128912,0000033213-26-000018,AccountsPayableCurrent,20241231,0,1177656000.0000,,33213,EQT CORP,1311,10-K
128913,0000033213-26-000018,AccountsPayableCurrent,20251231,0,1367431000.0000,,33213,EQT CORP,1311,10-K
128914,0000033213-26-000018,AccountsReceivableNetCurrent,20241231,0,1132608000.0000,,33213,EQT CORP,1311,10-K
128915,0000033213-26-000018,AccountsReceivableNetCurrent,20251231,0,1457959000.0000,,33213,EQT CORP,1311,10-K
128916,0000033213-26-000018,AccrualForEnvironmentalLossContingencies,20251231,0,4000000.0000,,33213,EQT CORP,1311,10-K
...,...,...,...,...,...,...,...,...,...,...
4986389,0002074176-26-000010,WeightedAverageNumberOfSharesOutstandingBasic,20231231,4,74176000.0000,,2074176,"VIPER ENERGY, INC.",1311,10-K
4986390,0002074176-26-000010,WeightedAverageNumberOfSharesOutstandingBasic,20241231,4,93932000.0000,,2074176,"VIPER ENERGY, INC.",1311,10-K
4986391,0002074176-26-000010,WeightedAverageNumberOfSharesOutstandingBasic,20241231,4,93932000.0000,,2074176,"VIPER ENERGY, INC.",1311,10-K
4986392,0002074176-26-000010,WeightedAverageNumberOfSharesOutstandingBasic,20251231,4,142530000.0000,,2074176,"VIPER ENERGY, INC.",1311,10-K
4986393,0002074176-26-000010,WeightedAverageNumberOfSharesOutstandingBasic,20251231,4,142530000.0000,,2074176,"VIPER ENERGY, INC.",1311,10-K

In [31]:
debt_ebitda_data = joinedFactsAndSubmissionsAnnual[
    joinedFactsAndSubmissionsAnnual['tag'].str.contains('Debt', case=False, na=False) &
    joinedFactsAndSubmissionsAnnual['tag'].str.contains('EBITDA', case=False, na=False)
]
debt_ebitda_data['tag'].unique()

array(['DebtInstrumentCovenantComplianceRatioOfConsolidatedNetDebtToConsolidatedEBITDA',
       'DebtInstrumentCovenantEBITDARatioMaximum',
       'DebtInstrumentCovenantEBITDARatioQuarterlyDecrease',
       'DebtInstrumentCovenantNetDebtToConsolidatedAdjustedEBITDARatio',
       'NetDebtToConsolidatedAdjustedEBITDARatio',
       'DebtInstrumentCovenantNetDebtToEBITDARatioMaximum',
       'RatioOfIndebtednessToEBITDA', 'DebtInstrumentEBITDARatioCovenant',
       'DebtInstrumentCovenantMaximumDebtToEBITDARatio',
       'DebtInstrumentCovenantEBITDAToInterestExpenseRatioMaximum',
       'DebtInstrumentCovenantMinimumPermittedAcquisitionAlternativeRequirementsForIndebtednessToEBITDARatio',
       'DebtInstrumentCovenantSeniorSecuredNetIndebtednessToAdjustedEBITDARatioMaximum',
       'DebtInstrumentNumberOfInstancesRatioOfDebtToEBITDAExceeded',
       'DebtInstrumentRatioOfDebtToEBITDA',
       'DebtInstrumentRatioOfDebtToEBITDAAfterAcquisition',
       'MaximumRatioOfDebtToEBITDA',
       'MaximumRatioOfDebtToEBITDAAfterAcquisition',
       'DebtCovenantAmountOfNonCapitalizedUndergroundMineDevelopmentCostsToBeExcludedFromEBITDA',
       'DebtInstrumentCovenantMaximumNetDebtToEBITDARatio',
       'DebtInstrumentCovenantConsolidatedEBITDAtoInterestExpenseRatioMinimum',
       'DebtInstrumentCovenantDebtToEBITDARatio',
       'DebtInstrumentCovenantDebttoEBITDARatio',
       'DebtInstrumentCovenantDebttoEBITDARatioafterstepuptriggeredbyacquisition',
       'DebtInstrumentCovenantConsolidatedEBITDARatioMaximum',
       'LitigationAndDebtExclusionFromEbitda',
       'DebtCovenantMinimumConsolidatedEBITDA',
       'CovenantRatioDebtEbitdaMaximumNumerator',
       'DebtCovenantRatioMaximumDebtToEBITDA',
       'DebtCovenantRatioMinimumEBITDAToInterestCharges',
       'DebtInstrumentCovenantAdjustedEBITDAThreshold',
       'DebtInstrumentCovenantNetDebtToEBITDARatio',
       'DebtInstrumentConsolidatedEBITDAPercentageToBeFunded',
       'DebtInstrumentCovenantMaximumRequiredAdjustmentEBITDA',
       'RatioOfIndebtednessToAnnualizedConsolidateAdjustedEbitda',
       'RatioOfTotalDebtAndNetHedgeExposureToAnnualizedBorrowerEbitda',
       'RatioOfTotalDebtToAnnualizedBorrowerEbitda',
       'DebtInstrumentCovenantIndebtednessToAdjustedEBITDAMaximumFromAcquisitions',
       'IndebtednessToAdjustedEbitdaCurrent',
       'IndebtednesstoAdjustedEBITDAMaximum',
       'DebtInstrumentCovenantEarningsBeforeInterestTaxesDepreciationAndAmortizationOrEBITDAToFixedChargesMinimum',
       'DebtInstrumentCoverageRatioDebtToEBITDAAcquisitionPeriodMaximum',
       'DebtInstrumentCoverageRatioDebtToEBITDAMaximum',
       'DebtInstrumentCovenantEBITDAMinimum',
       'DebtInstrumentCovenantEBITDAMinimumFiscalQuarterPeriod',
       'DebtInstrumentCovenantConsolidatedIndebtednessToConsolidatedEBITDAMaximum',
       'DebtInstrumentCovenantEBITDALessCapitalExpendituresToConsolidatedCashInterestExpenseRatioMinimum',
       'LineOfCreditFacilityCovenantComplianceDebtToEBITDAXRatio',
       'NetDebtToEbitdaExcludingRestructuringAndOtherCostsRatio',
       'NetDebtToEbitdaExcludingRestructuringAndOtherCostsRatioLongTermTarget',
       'NetDebtToEbitdaExcludingRestructuringAndOtherCostsRatioTarget',
       'TotalNetFundedDebtToAdjustedEBITDARatio',
       'DebtInstrumentCovenantNetEarningsUsedForCalculationOfCreditFacilityAdjustedEBITDANumberOfQuarters',
       'DebtInstrumentEBITDARRatio',
       'DebtInstrumentCovenantRatioEBITDAToFixedChargesMinimum',
       'DebtInstrumentPercentageOfConsolidatedAdjustedEbitda',
       'FinancialCovenantsDebtToEbitdaxRatio',
       'DebtInstrumentCovenantRatioEBITDAToInterestExpense',
       'DebtInstrumentCovenantMinimumDebtToEBITDARatio',
       'DebtInstrumentCovenantMinimumDebtToEBITDARatioUponConsummationOfAcquisition',
       'DebtInstrumentNumberOfConsecutiveFiscalQuartersMinimumDebtToEBITDARatio',
       'DebtInstrumentNumberOfConsecutiveFiscalQuartersMinimumDebtToEBITDARatioUponConsummationOfAcquisition',
       'DebtInstrumentCovenantAdjustedEBITDAToInterestExpenseRatio',
       'LongTermDebtThresholdForEBITDARatioIncreaseToElection',
       'DebtToEBITDARequired',
       'DebtInstrumentCovenantTotalDebtToConsolidatedEBITDARatio',
       'NetDebtToEBITDARatio', 'RatioOfIndebtednessToConsolidatedEBITDA',
       'DebtToEbitdaRatioMaximum', 'NetDebtToEbitdaRatio',
       'DebtCovenantRatioOfDebtToEBITDAX', 'DebtToEbitda',
       'Bank-AdjustedNetDebtToEBITDARatio',
       'IndebtednessToAdjustedEBITDARatio',
       'DebtInstrumentCovenantIndebtednessToEBITDAXRatioMaximum',
       'IncrementalDebtAmountMaximumPercentageOfConsolidatedEBITDA',
       'DebtCovenantRatioofFundedIndebtednesstoEBITDA',
       'DebtInstrumentCovenantRatioofConsolidatedTotalDebttoConsolidatedEBITDA',
       'DebtInstrumentCovenantAdjustedConsolidatedTotalDebtToConsolidatedEBITDARatio',
       'DebtInstrumentCovenantAdjustedConsolidatedTotalDebtToConsolidatedEBITDARatioFollowingMaterialAcquisition',
       'DebtInstrumentCovenantConsolidatedEBITDAToInterestExpenseRatio',
       'ActualDebtToEbitdaRatio', 'ActualSecuredDebtToEbitdaRatio',
       'DebtInstrumentConvertibleThresholdPercentageOfLastTwelveMonthEBITDA',
       'DebtInstrumentFinancialCovenantMaximumSeniorSecuredDebtToEbitda',
       'DebtInstrumentFinancialCovenantMaximumTotalDebttoEBITDARatio',
       'DebtInstrumentFinancialCovenantMinimumEBITDAtoTotalInterestExpensesRatio',
       'NetDebtToEBITDALeverageRatioCovenantLineOfCredit',
       'DebtInstrumentCovenantComplianceLeverageRatioNetDebtToAdjustedEBITDA',
       'DebtInstrumentCovenantMinimumEbitdaAndAssetsOfSubsidiaries',
       'DebtInstrumentCovenantMinimumEbitdaOfGuarantors',
       'DebtInstrumentCovenantEBITDA', 'DebtToEBITDARatio',
       'DebtToEbitdaRatioForNextFiscalYear',
       'DebtInstrumentCovenantsConsolidatedEBITDAPercentage',
       'DebtInstrumentCovenantDebtToEBITDARatioRequiredMaximum',
       'DebtInstrumentCovenantFutureDebtToEBITDARatioRequiredMaximum',
       'CovenantRatioDebtToEbitda',
       'CovenantRatioDebtToEbitdaPostAcquisition',
       'LineofCreditFacilityCovenantDebttoEBITDARatio',
       'DebtInstrumentCovenantComplianceMaximumRatioOfIndebtednessToEbitda',
       'DebtInstrumentCovenantComplianceMaximumRatioOfIndebtednessToEBITDAFollowingMaterialAcquisition',
       'DebtInstrumentCovenantMaximumFundedDebtToEBITDARatio',
       'DebtInstrumentCovenantMinimumEBITDAToInterestCoverageRatio',
       'DebtInstrumentCovenantMinimumFundedDebtToEBITDARatio',
       'DebtInstrumentSecuredIndebtednessToEBITDARatio',
       'DebtInstrumentCovenantLeverageRatioToEBITDAMaximum',
       'LeverageRatioConsolidatedIndebtednessConsolidatedAdjustmentEbitda',
       'LeverageRatioConsolidatedIndebtednessConsolidatedAdjustmentEbitdaActual',
       'DebtInstrumentCovenantRatioOfAdjustedEBITDAToFixedChargesMinimum',
       'DebtInstrumentCovenantDebttoEBITDAMaximum',
       'DebtInstrumentCovenantEBITDAtoInterestRatioMinimum',
       'LineofCreditFacilityCovenantTermsMaximumDebttoEBITDARatio',
       'LineOfCreditFacilityCovenantTermsStepDownDebtToEBITDARatio',
       'DebtInstrumentCovenantEBITDARatio',
       'DebtInstrumentCovenantRatioOfEBITDAToFixedCharges',
       'DebtInstrumentCovenantConsolidatedNetGEBVIndebtednessToConsolidatedGEBVEBITDARatioMinimum',
       'DebtInstrumentCovenantAdjustedConsolidatedTotalNetDebtToConsolidatedAdjustedEBITDARatioMaximum',
       'DebtInstrumentCovenantFollowingAQualifiedAcquisitionAdjustedConsolidatedTotalNetDebtToConsolidatedAdjustedEBITDARatioMaximum',
       'RatioofIndebtednesstoEBITDA',
       'DebtInstrumentCovenantConsolidatedDebtToConsolidatedEBITDARatio',
       'DebtInstrumentCovenantConsolidatedEBITDAPercent',
       'InitialConsolidatedNetDebtToConsolidatedEbitdaRatio',
       'ShareBasedCompensationArrangementByShareBasedPaymentAwardNetDebtToAdjustedEBITDAPercentageOfPerformanceLevel',
       'IncreaseToMaximumRatioOfIndebtednessToEbitda',
       'RatioOfIndebtednessToEbitda',
       'DebtInstrumentCovenantConsolidatedEBITDA',
       'DebtInstrumentCovenantSeniorSecuredIndebtednessToConsolidatedEBITDARatioMaximum',
       'DebtInstrumentOptionToIncreaseCommitmentsByConsolidatedEBITDAPercentage',
       'DebtInstrumentDebtCovenantConsolidatedTotalDebtToConsolidatedEBITDAIncreaseDueToMaterialAcquisition',
       'DebtInstrumentDebtCovenantConsolidatedTotalDebtToConsolidatedEBITDAIncreaseDueToMaterialAcquisitionMaximum',
       'DebtInstrumentCovenantDebtToConsolidatedEBITDARatioPeriodOne',
       'DebtInstrumentCovenantDebtToConsolidatedEBITDARatioPeriodTwo',
       'DebtInstrumentCovenantMaximumConsolidatedNetLeverageRatioOfDebtToConsolidatedEBITDA',
       'MaximumRatioOfConsolidatedFundedDebtToConsolidatedEBITDA',
       'DebtInstrumentCovenantEBITDAPlusLeaseExpensesToFixedCharges',
       'DebtInstrumentCovenantNetLeverageEBITDAToProFormaEBITDARatioMaximum',
       'DebtInstrumentCovenantProFormaAdjustedEBITDAToCashInterestExpenseRatioMaximum',
       'DebtInstrumentCovenantAdditionalDividendPercentOfEBITDAR',
       'DebtInstrumentFinancialCovenantMinimumAdjustedEBITDAR',
       'DebtInstrumentCovenantNetDebtToEBITDARatioStepUp',
       'DebtInstrumentAccordionFeaturePercentageOfConsolidatedEBITDA',
       'DebtInstrumentCovenantAmountToEBITDA',
       'DebtInstrumentCovenantTriggerEventEBITDAMinimum',
       'DebtInstrumentCovenantComplianceAdjustedEBITDAPlusLeaseExpenseToFixedCharges',
       'DebtInstrumentCovenantComplianceTotalDebtToAdjustedEBITDA',
       'CreditAdjustedEBITDANetDebt',
       'DebtInstrumentEBITDACalculatedThreshold',
       'DebtInstrumentCovenantTotalDebtToEBITDAXRatioMaximum',
       'DebtInstrumentCovenantMaximumNetDebtToEBITDA',
       'DebtInstrumentCovenantTotalDebtToEBITDARatioMinimum'],
      dtype=object)

In [32]:
count = len(debt_ebitda_data[debt_ebitda_data['tag'] == 'DebtInstrumentCovenantComplianceRatioOfConsolidatedNetDebtToConsolidatedEBITDA'])
print(f"NetDebtToEBITDARatio appears {count} times")

NetDebtToEBITDARatio appears 2 times

In [33]:
# Define the tags you want to check
debt_ebitda_tags = [
    'DebtInstrumentCovenantComplianceRatioOfConsolidatedNetDebtToConsolidatedEBITDA',
    'NetDebtToEBITDARatio',
    'DebtToEbitda',
    'ActualDebtToEbitdaRatio',
    'DebtInstrumentCovenantDebtToEBITDARatio',
    'DebtInstrumentCovenantMaximumDebtToEBITDARatio',
    'DebtInstrumentCovenantNetDebtToEBITDARatio',
    'RatioOfIndebtednessToEBITDA',
    'DebtInstrumentCovenantConsolidatedIndebtednessToConsolidatedEBITDAMaximum',
    'DebtToEbitdaRatioMaximum'
]

# Count occurrences for each tag
for tag in debt_ebitda_tags:
    count = (joinedFactsAndSubmissionsAnnual['tag'] == tag).sum()
    if count > 0:
        print(f"{tag}: {count} times")
    else:
        print(f"{tag}: NOT FOUND")

DebtInstrumentCovenantComplianceRatioOfConsolidatedNetDebtToConsolidatedEBITDA: 2 times
NetDebtToEBITDARatio: 1 times
DebtToEbitda: 2 times
ActualDebtToEbitdaRatio: 1 times
DebtInstrumentCovenantDebtToEBITDARatio: 3 times
DebtInstrumentCovenantMaximumDebtToEBITDARatio: 12 times
DebtInstrumentCovenantNetDebtToEBITDARatio: 1 times
RatioOfIndebtednessToEBITDA: 2 times
DebtInstrumentCovenantConsolidatedIndebtednessToConsolidatedEBITDAMaximum: 1 times
DebtToEbitdaRatioMaximum: 1 times

In [34]:
filtered_data = joinedFactsAndSubmissionsAnnual[joinedFactsAndSubmissionsAnnual['tag'].isin(debt_ebitda_tags)]
filtered_data

,adsh,tag,ddate,qtrs,value,footnote,cik,name,sic,form
4698,0000004281-26-000012,DebtInstrumentCovenantComplianceRatioOfConsoli...,20230731,0,3.7500,,4281,HOWMET AEROSPACE INC.,3350,10-K
4699,0000004281-26-000012,DebtInstrumentCovenantComplianceRatioOfConsoli...,20251231,4,3.7500,,4281,HOWMET AEROSPACE INC.,3350,10-K
235101,0000058492-26-000107,RatioOfIndebtednessToEBITDA,20251231,0,3.5000,,58492,LEGGETT & PLATT INC,2510,10-K
235102,0000058492-26-000107,RatioOfIndebtednessToEBITDA,20251231,0,4.0000,,58492,LEGGETT & PLATT INC,2510,10-K
398156,0000093389-26-000012,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20251231,0,1.0000,,93389,"STANDARD MOTOR PRODUCTS, INC.",3714,10-K
717814,0000798354-26-000009,DebtInstrumentCovenantDebtToEBITDARatio,20251231,0,3.7500,,798354,FISERV INC,7389,10-K
1138604,0001000623-26-000016,DebtInstrumentCovenantNetDebtToEBITDARatio,20241231,0,5.0000,,1000623,"MATIV HOLDINGS, INC.",2621,10-K
1453791,0001100682-26-000022,DebtInstrumentCovenantConsolidatedIndebtedness...,20241231,0,4.2500,,1100682,"CHARLES RIVER LABORATORIES INTERNATIONAL, INC.",8731,10-K
1485568,0001104659-26-012049,DebtInstrumentCovenantDebtToEBITDARatio,20251231,4,3.7500,,823768,WASTE MANAGEMENT INC,4953,10-K
1485569,0001104659-26-012049,DebtInstrumentCovenantDebtToEBITDARatio,20251231,4,3.7500,,823768,WASTE MANAGEMENT INC,4953,10-K
2190348,0001193125-26-063960,NetDebtToEBITDARatio,20220831,0,0.3500,,1519751,"FORTUNE BRANDS INNOVATIONS, INC.",2430,10-K
2199130,0001193125-26-064113,DebtToEbitdaRatioMaximum,20251231,4,0.0350,,871763,MANPOWERGROUP INC.,7363,10-K
2316615,0001193125-26-071672,DebtToEbitda,20251231,4,0.0100,,1795139,GREEN THUMB INDUSTRIES INC.,0100,10-K
2316616,0001193125-26-071672,DebtToEbitda,20251231,4,0.0350,,1795139,GREEN THUMB INDUSTRIES INC.,0100,10-K
2852375,0001296445-26-000006,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20231231,0,6.0000,,1296445,"ORMAT TECHNOLOGIES, INC.",4911,10-K
2852376,0001296445-26-000006,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20231231,0,6.0000,,1296445,"ORMAT TECHNOLOGIES, INC.",4911,10-K
2852377,0001296445-26-000006,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20240531,0,6.0000,,1296445,"ORMAT TECHNOLOGIES, INC.",4911,10-K
2852378,0001296445-26-000006,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20240930,0,6.0000,,1296445,"ORMAT TECHNOLOGIES, INC.",4911,10-K
2852379,0001296445-26-000006,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20250131,0,6.0000,,1296445,"ORMAT TECHNOLOGIES, INC.",4911,10-K
2852380,0001296445-26-000006,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20250331,0,6.0000,,1296445,"ORMAT TECHNOLOGIES, INC.",4911,10-K
2852381,0001296445-26-000006,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20250430,0,6.0000,,1296445,"ORMAT TECHNOLOGIES, INC.",4911,10-K
2852382,0001296445-26-000006,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20250630,0,6.0000,,1296445,"ORMAT TECHNOLOGIES, INC.",4911,10-K
2852383,0001296445-26-000006,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20251231,0,6.0000,,1296445,"ORMAT TECHNOLOGIES, INC.",4911,10-K
2951306,0001345126-26-000026,ActualDebtToEbitdaRatio,20251231,4,5.4700,,1345126,COMPASS DIVERSIFIED HOLDINGS,2510,10-K
4008871,0001628280-26-009136,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20251231,4,4.0000,,1059556,MOODYS CORP /DE/,7320,10-K
4008872,0001628280-26-009136,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20251231,4,4.5000,,1059556,MOODYS CORP /DE/,7320,10-K

In [35]:
filtered_data

,adsh,tag,ddate,qtrs,value,footnote,cik,name,sic,form
4698,0000004281-26-000012,DebtInstrumentCovenantComplianceRatioOfConsoli...,20230731,0,3.7500,,4281,HOWMET AEROSPACE INC.,3350,10-K
4699,0000004281-26-000012,DebtInstrumentCovenantComplianceRatioOfConsoli...,20251231,4,3.7500,,4281,HOWMET AEROSPACE INC.,3350,10-K
235101,0000058492-26-000107,RatioOfIndebtednessToEBITDA,20251231,0,3.5000,,58492,LEGGETT & PLATT INC,2510,10-K
235102,0000058492-26-000107,RatioOfIndebtednessToEBITDA,20251231,0,4.0000,,58492,LEGGETT & PLATT INC,2510,10-K
398156,0000093389-26-000012,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20251231,0,1.0000,,93389,"STANDARD MOTOR PRODUCTS, INC.",3714,10-K
717814,0000798354-26-000009,DebtInstrumentCovenantDebtToEBITDARatio,20251231,0,3.7500,,798354,FISERV INC,7389,10-K
1138604,0001000623-26-000016,DebtInstrumentCovenantNetDebtToEBITDARatio,20241231,0,5.0000,,1000623,"MATIV HOLDINGS, INC.",2621,10-K
1453791,0001100682-26-000022,DebtInstrumentCovenantConsolidatedIndebtedness...,20241231,0,4.2500,,1100682,"CHARLES RIVER LABORATORIES INTERNATIONAL, INC.",8731,10-K
1485568,0001104659-26-012049,DebtInstrumentCovenantDebtToEBITDARatio,20251231,4,3.7500,,823768,WASTE MANAGEMENT INC,4953,10-K
1485569,0001104659-26-012049,DebtInstrumentCovenantDebtToEBITDARatio,20251231,4,3.7500,,823768,WASTE MANAGEMENT INC,4953,10-K
2190348,0001193125-26-063960,NetDebtToEBITDARatio,20220831,0,0.3500,,1519751,"FORTUNE BRANDS INNOVATIONS, INC.",2430,10-K
2199130,0001193125-26-064113,DebtToEbitdaRatioMaximum,20251231,4,0.0350,,871763,MANPOWERGROUP INC.,7363,10-K
2316615,0001193125-26-071672,DebtToEbitda,20251231,4,0.0100,,1795139,GREEN THUMB INDUSTRIES INC.,0100,10-K
2316616,0001193125-26-071672,DebtToEbitda,20251231,4,0.0350,,1795139,GREEN THUMB INDUSTRIES INC.,0100,10-K
2852375,0001296445-26-000006,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20231231,0,6.0000,,1296445,"ORMAT TECHNOLOGIES, INC.",4911,10-K
2852376,0001296445-26-000006,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20231231,0,6.0000,,1296445,"ORMAT TECHNOLOGIES, INC.",4911,10-K
2852377,0001296445-26-000006,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20240531,0,6.0000,,1296445,"ORMAT TECHNOLOGIES, INC.",4911,10-K
2852378,0001296445-26-000006,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20240930,0,6.0000,,1296445,"ORMAT TECHNOLOGIES, INC.",4911,10-K
2852379,0001296445-26-000006,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20250131,0,6.0000,,1296445,"ORMAT TECHNOLOGIES, INC.",4911,10-K
2852380,0001296445-26-000006,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20250331,0,6.0000,,1296445,"ORMAT TECHNOLOGIES, INC.",4911,10-K
2852381,0001296445-26-000006,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20250430,0,6.0000,,1296445,"ORMAT TECHNOLOGIES, INC.",4911,10-K
2852382,0001296445-26-000006,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20250630,0,6.0000,,1296445,"ORMAT TECHNOLOGIES, INC.",4911,10-K
2852383,0001296445-26-000006,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20251231,0,6.0000,,1296445,"ORMAT TECHNOLOGIES, INC.",4911,10-K
2951306,0001345126-26-000026,ActualDebtToEbitdaRatio,20251231,4,5.4700,,1345126,COMPASS DIVERSIFIED HOLDINGS,2510,10-K
4008871,0001628280-26-009136,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20251231,4,4.0000,,1059556,MOODYS CORP /DE/,7320,10-K
4008872,0001628280-26-009136,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20251231,4,4.5000,,1059556,MOODYS CORP /DE/,7320,10-K

In [36]:
Interest_Coverage_Ratio = joinedFactsAndSubmissionsAnnual[
    joinedFactsAndSubmissionsAnnual['tag'].str.contains('Interest', case=False, na=False) &
    joinedFactsAndSubmissionsAnnual['tag'].str.contains('Coverage', case=False, na=False) & 
    joinedFactsAndSubmissionsAnnual['tag'].str.contains('Ratio', case=False, na=False)
]
Interest_Coverage_Ratio['tag'].unique()

array(['DebtInstrumentCovenantInterestCoverageRatioMinimum',
       'DebtInstrumentCovenantInterestCoverageRatio',
       'DebtInstrumentCovenantInterestCoverageRatioRequirementMinimum',
       'DebtInstrumentCovenantComplianceUnencumberedInterestCoverageRatio',
       'MinimumInterestCoverageRatio',
       'DebtInstrumentInterestCoverageRatio',
       'DebtInstrumentInterestCoverageRatioRequired',
       'DebtInstrumentCovenantDescriptionMinimumInterestCoverageRatio',
       'LineofCreditFacilityCovenantComplianceActualInterestCoverageRatio',
       'DebtInstrumentCovenantInterestRateCoverageRatioMaximum',
       'DebtInstrumentCovenantComplianceConsolidatedInterestCoverageRatio',
       'InterestCoverageRatio',
       'CovenantRequirementInterestCoverageRatio',
       'DebtInstrumentCovenantTermsConsolidatedInterestCoverageRatio',
       'DebtInstrumentCovenantTermsMinimumInterestCoverageRatio',
       'DebtCovenantMinimumConsolidatedInterestCoverageRatio',
       'CreditFacilityMinimumInterestCoverageRatio',
       'MinimumConsolidatedInterestCoverageRatio',
       'DebtInstrumentCovenantInterestCoverageRatioRequiredMinimum',
       'ConsolidatedInterestCoverageRatio', 'InterestCoverageRatioOfDebt',
       'InterestCoverageRatioRequiredMinimum',
       'MaximumInterestCoverageRatio',
       'LineOfCreditFacilityMinimumInterestCoverageRatioAfterCovenantReliefPeriod',
       'DebtInstrumentCovenantMinimumInterestCoverageRatio',
       'DebtInstrumentConsolidatedInterestCoverageRatio',
       'DebtInstrumentCovenantInterestCoverageRatioMaximum',
       'UnsecuredDebtInterestCoverageRatio',
       'LineOfCreditFacilityMinimumInterestCoverageRatio',
       'DebtInstrumentCovenantNumberOfFiscalQuartersApplicableToInterestCoverageRatio',
       'DebtInstrumentMinimumCovenantConsolidatedInterestCoverageRatio',
       'EarningsBeforeInterestTaxesDepreciationAndAmortizationExcludingRestructuringAndOtherCostsInterestCoverageRatio',
       'IncreaseDecreaseEbitdaExcludingRestructuringAndOtherCostsInterestCoverageRatioDueToChangeInNetInterestCosts',
       'CreditAgreementMinimumInterestCoverageRatio',
       'DebtInstrumentInterestCoverageRatioMinimum',
       'InterestChargeCoverageRatioCovenantTerm',
       'LineOfCreditFacilityCovenantTermsMinimumInterestCoverageRatio',
       'DebtInstrumentCovenantInterestCoverageRatioMaximumPercentage',
       'DebtInstrumentDebtCovenantUnencumberedInterestCoverageRatio',
       'DebtInstrumentCovenantTermsInterestCoverageRatio',
       'InterestCoverageRatioMinimumForCovenantCompliance',
       'DebtCovenantInterestCoverageRatio',
       'DebtCovenantInterestCoverageRatioStepUp',
       'LineOfCreditFacilityFinancialCovenantsCombinedInterestChargeCoverageRatio',
       'DebtInstrumentCovenantComplianceMinimumInterestCoverageRatio',
       'DebtInstrumentCovenantUnsecuredInterestCoverageRatio',
       'Debtinstrumentcovenantinterestcoverageratio',
       'LineOfCreditFacilityInterestCoverageRatioCovenant',
       'UnsecuredInterestCoverageRatio',
       'CurrentInterestCoverageRatioCovenantCompliance',
       'InterestCoverageRatioCovenantCompliance',
       'DebtInstrumentCovenantConsolidatedInterestCoverageRatio',
       'DividendRestrictionInterestCoverageRatio',
       'LineofCreditFacilityCovenantTermsMinimumInterestCoverageRatio',
       'InterestCoverageMinimumRatioCovenantLineOfCredit',
       'DebtInstrumentCovenantConsolidatedInterestCoverageRatioMinimum',
       'CovenantMinimumInterestCoverageRatio',
       'LineOfCreditFacilityCovenantTermsMinimumConsolidatedInterestCoverageRatioRequired',
       'InterestAndDividendCoverageRatio',
       'DebtInstrumentCovenantMinimumConsolidatedInterestCoverageRatio',
       'DebtInstrumentCovenantComplianceRatioofInterestCoverage',
       'RatioofInterestCoverage',
       'DebtInstrumentCovenantComplianceMinimumUnsecuredInterestCoverageRatio',
       'DebtInstrumentCovenantComplianceMinimumUnsecuredInterestCoverageRatioActual',
       'MinimumUnsecuredInterestCoverageRatio',
       'DebtInstrumentCovenantMinimumUnsecuredInterestCoverageRatio',
       'DebtInstrumentCovenantMinimumEBITDAToInterestCoverageRatio',
       'DebtInstrumentConsolidatedInterestCoverageRatioMinimum',
       'DebtInstrumentCovenantInterestCoverageRatioMinimumScenarioOne',
       'DebtInstrumentCovenantInterestCoverageRatioMinimumScenarioTwo',
       'DebtInstrumentCovenantActualInterestCoverageRatio',
       'DebtInstrumentCovenantConsolidatedInterestCoverageRatioActual',
       'InterestOnlyDebtServiceCoverageRatioDefaultEvent',
       'InterestOnlyDebtServiceCoverageRatioManagerTerminationEvent',
       'DebtInstrumentCovenantCashInterestCoverageRatioMinimumThreshold',
       'DebtInstrumentCovenantUnsecuredInterestCoverageRatioMinimum',
       'DebtInstrumentCovenantInterestCoverageRatioThresholdForFourConsecutiveFiscalQuarters',
       'DebtInstrumentCovenantFixedInterestCoverageRatio',
       'DebtInstrumentCashInterestCoverageRatioFollowingCovenantTriggerEventMinimum',
       'LoanCovenantsMinimumInterestCoverageRatio',
       'DebtInstrumentCovenantInterestRentCoverageRatioMinimum',
       'DebtInstrumentInterestRateIncreaseAssetCoverageRatioThreshold'],
      dtype=object)

In [37]:
# Define the tags you want to check
Interest_Coverage_Ratio_tags = [
    'InterestCoverageRatio',
    'ConsolidatedInterestCoverageRatio',
    'DebtInstrumentCovenantActualInterestCoverageRatio',
    'DebtInstrumentCovenantComplianceConsolidatedInterestCoverageRatio',
    'DebtInstrumentCovenantInterestCoverageRatio',
    'DebtInstrumentCovenantMinimumInterestCoverageRatio',
    'DebtInstrumentConsolidatedInterestCoverageRatio',
    'DebtInstrumentCovenantComplianceMinimumInterestCoverageRatio',
    'LineofCreditFacilityCovenantComplianceActualInterestCoverageRatio',
    'DebtInstrumentCovenantConsolidatedInterestCoverageRatioMinimum'
]

# Count occurrences for each tag
for tag in Interest_Coverage_Ratio_tags:
    count = (joinedFactsAndSubmissionsAnnual['tag'] == tag).sum()
    if count > 0:
        print(f"{tag}: {count} times")
    else:
        print(f"{tag}: NOT FOUND")

InterestCoverageRatio: 23 times
ConsolidatedInterestCoverageRatio: 5 times
DebtInstrumentCovenantActualInterestCoverageRatio: 1 times
DebtInstrumentCovenantComplianceConsolidatedInterestCoverageRatio: 5 times
DebtInstrumentCovenantInterestCoverageRatio: 34 times
DebtInstrumentCovenantMinimumInterestCoverageRatio: 10 times
DebtInstrumentConsolidatedInterestCoverageRatio: 2 times
DebtInstrumentCovenantComplianceMinimumInterestCoverageRatio: 1 times
LineofCreditFacilityCovenantComplianceActualInterestCoverageRatio: 1 times
DebtInstrumentCovenantConsolidatedInterestCoverageRatioMinimum: 3 times

In [38]:
filtered_data1 = joinedFactsAndSubmissionsAnnual[joinedFactsAndSubmissionsAnnual['tag'].isin(Interest_Coverage_Ratio_tags)]
filtered_data = pd.concat([filtered_data, filtered_data1], ignore_index=True)
filtered_data

,adsh,tag,ddate,qtrs,value,footnote,cik,name,sic,form
0,0000004281-26-000012,DebtInstrumentCovenantComplianceRatioOfConsoli...,20230731,0,3.7500,,4281,HOWMET AEROSPACE INC.,3350,10-K
1,0000004281-26-000012,DebtInstrumentCovenantComplianceRatioOfConsoli...,20251231,4,3.7500,,4281,HOWMET AEROSPACE INC.,3350,10-K
2,0000058492-26-000107,RatioOfIndebtednessToEBITDA,20251231,0,3.5000,,58492,LEGGETT & PLATT INC,2510,10-K
3,0000058492-26-000107,RatioOfIndebtednessToEBITDA,20251231,0,4.0000,,58492,LEGGETT & PLATT INC,2510,10-K
4,0000093389-26-000012,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20251231,0,1.0000,,93389,"STANDARD MOTOR PRODUCTS, INC.",3714,10-K
...,...,...,...,...,...,...,...,...,...,...
106,0001673985-26-000008,DebtInstrumentCovenantConsolidatedInterestCove...,20211031,0,3.0000,,1673985,ADVANSIX INC.,2821,10-K
107,0001757073-26-000011,InterestCoverageRatio,20251231,0,3.0000,,1757073,ENVISTA HOLDINGS CORP,3843,10-K
108,0001895262-26-000076,DebtInstrumentCovenantInterestCoverageRatio,20230430,0,2.5000,,1895262,NOBLE CORP PLC,1381,10-K
109,0001941365-26-000006,DebtInstrumentCovenantMinimumInterestCoverageR...,20240630,0,3.0000,,1941365,"MASTERBRAND, INC.",2511,10-K
110,0002089661-26-000016,DebtInstrumentCovenantInterestCoverageRatio,20251231,0,2.2500,,2089661,SUNOCOCORP LLC,2911,10-K

In [39]:
Current_Ratio = joinedFactsAndSubmissionsAnnual[
    joinedFactsAndSubmissionsAnnual['tag'].str.contains('Current', case=False, na=False) &
    joinedFactsAndSubmissionsAnnual['tag'].str.contains('Ratio', case=False, na=False)
]
Current_Ratio['tag'].unique()

array(['AssetAcquisitionConsiderationTransferredPercentOfActualPremiumsWrittenDuringCurrentYear',
       'BusinessCombinationContingentConsiderationLiabilityNoncurrent',
       'BusinessCombinationContingentConsiderationLiabilityCurrent',
       'AssetsOfDisposalGroupIncludingDiscontinuedOperationCurrent',
       'DisposalGroupIncludingDiscontinuedOperationDeferredRevenueCurrent',
       'DisposalGroupIncludingDiscontinuedOperationOtherCurrentAssets',
       'DisposalGroupIncludingDiscontinuedOperationOtherCurrentLiabilities',
       'DisposalGroupIncludingDiscontinuedOperationOtherNoncurrentAssets',
       'DisposalGroupIncludingDiscontinuedOperationPropertyPlantAndEquipmentCurrent',
       'LiabilitiesOfDisposalGroupIncludingDiscontinuedOperationCurrent',
       'BusinessCombinationContingentConsiderationLiabilityNoncurrentEarnoutPaymentsFairValue',
       'BusinessCombinationContingentConsiderationLiabilityNoncurrentFinalPaymentFairValue',
       'SupplierFinanceProgramObligationCurrentStatementOfFinancialPositionExtensibleEnumerationNotDisclosedFlag',
       'DisposalGroupIncludingDiscontinuedOperationAccountsPayableCurrent',
       'DisposalGroupIncludingDiscontinuedOperationInventoryCurrent',
       'DisposalGroupIncludingDiscontinuedOperationPrepaidAndOtherAssetsCurrent',
       'DisposalGroupIncludingDiscontinuedOperationOtherNoncurrentLiabilities',
       'FinancingReceivableCreditQualityCurrentCombinedLoanToValueRatioPercentageMaximum',
       'FinancingReceivableCreditQualityCurrentLoanToValueRatioPercentageMaximum',
       'DisposalGroupIncludingDiscontinuedOperationAccruedPayrollAndBenefitsLiabilitiesCurrent',
       'DisposalGroupIncludingDiscontinuedOperationAssetsNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationContractAssetsCurrent',
       'DisposalGroupIncludingDiscontinuedOperationDeferredChargesAndOtherAssetsNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationLongTermDebtNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationLongTermLeaseObligationNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationNotesPayableAndCurrentMaturitiesOfLongTermDebtCurrent',
       'DisposalGroupIncludingDiscontinuedOperationOperatingLeaseRightOfUseAssetNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationPropertyPlantAndEquipmentNoncurrent',
       'LiabilitiesOfDisposalGroupIncludingDiscontinuedOperationNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationAccountsReceivableAllowanceForCreditLossCurrent',
       'DisposalGroupIncludingDiscontinuedOperationCurrentMaturitiesOfLongTermDebtNet',
       'DisposalGroupIncludingDiscontinuedOperationLongTermDebtExcludingCurrentMaturities',
       'DisposalGroupIncludingDiscontinuedOperationPrepaidLoggingRoadsCurrent',
       'DisposalGroupIncludingDiscontinuedOperationDeferredTaxesNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationOperatingLeaseLiabilitiesCurrent',
       'DisposalGroupIncludingDiscontinuedOperationOperatingLeaseLiabilitiesNoncurrent',
       'DebtServiceCoverageRatioCurrentFiscalYear',
       'DebtServiceCoverageRatioOriginatedMoreThanFiveYearsBeforeCurrentFiscalYear',
       'DebtServiceCoverageRatioYearFiveOriginatedFourYearsBeforeCurrentFiscalYear',
       'DebtServiceCoverageRatioYearFourOriginatedThreeYearsBeforeCurrentFiscalYear',
       'DebtServiceCoverageRatioYearThreeOriginatedTwoYearsBeforeCurrentFiscalYear',
       'DebtServiceCoverageRatioYearTwoOriginatedFiscalYearBeforeCurrentFiscalYear',
       'DisposalGroupIncludingDiscontinuedOperationGoodwillCurrent',
       'DisposalGroupIncludingDiscontinuedOperationGoodwillNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationInsuranceSettlementsReceivableCurrent',
       'DisposalGroupIncludingDiscontinuedOperationInsuranceSettlementsReceivableNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationNotesLoansAndFinancingReceivableNetInsuranceCompaniesCurrent',
       'DisposalGroupIncludingDiscontinuedOperationNotesLoansAndFinancingReceivableNetInsuranceCompaniesNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationProductLiabilityCurrent',
       'DisposalGroupIncludingDiscontinuedOperationProductLiabilityNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationsContractWithCustomerLiabilityCurrent',
       'DisposalGroupIncludingDiscontinuedOperationAccruedLiabilitiesCurrent',
       'DisposalGroupIncludingDiscontinuedOperationContractLiabilitiesCurrent',
       'DisposalGroupIncludingDiscontinuedOperationDebtCurrent',
       'DisposalGroupIncludingDiscontinuedOperationDebtNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationInventoryFinishedAndInProcessCurrent',
       'DisposalGroupIncludingDiscontinuedOperationInventoryMaterialsAndSuppliesCurrent',
       'DisposalGroupIncludingDiscontinuedOperationOtherReceivablesCurrent',
       'DisposalGroupIncludingDiscontinuedOperationsAccountsReceivableAllowanceForCreditLossCurrent',
       'AccruedVoluntarySeparationProgramAndSeverancePayCurrent',
       'BusinessCombinationContingentConsiderationPercentOfSalesLiabilityNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationAccountsPayableAndAccruedLiabilitiesCurrent',
       'LiabilityforClaimsAndClaimsAdjustmentExpenseLossRatioinPercentageCurrentYearEstimatedLoss',
       'DisposalGroupIncludingDiscontinuedOperationIntangibleAssetsNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationOperatingLeaseAssetsNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationOperatingLeaseLiabilityNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationPayrollAndBenefitRelatedLiabilitiesCurrentCurrent',
       'Collaborationpartnersharecurrent',
       'BusinessAcquisitionContingentConsiderationCurrentFairValue',
       'NoncurrentIncomeTaxExpenseBenefitContinuingOperations',
       'AccruedPurchaseConsiderationCurrent',
       'DisposalGroupIncludingDiscontinuedOperationPropertyPlantAndEquipmentAccumulatedDepreciationDepletionAndAmortizationNoncurrent',
       'NumberOfSitesAssociatedWithFormerAndCurrentOperationLocations',
       'BusinessCombinationContingentConsiderationAssetCurrent',
       'DisposalGroupIncludingDiscontinuedOperationContingentConsiderationReceivableNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationDeferredCashConsiderationNoncurrent',
       'DeferredTaxAssetValuationAllowanceCurrentYearOperationsIncreaseDecrease',
       'CurrentDebtServiceCoverageRatioHigherRiskLoans1',
       'DisposalGroupIncludingDiscontinuedOperationAccruedCompensationCurrent',
       'DisposalGroupIncludingDiscontinuedOperationAccruedExpensesAndOtherLiabilitiesCurrent',
       'DisposalGroupIncludingDiscontinuedOperationIntangibleAssetsCurrent',
       'DisposalGroupIncludingDiscontinuedOperationValuationAllowanceCurrent',
       'FinancingReceivableRatioOfNonperformingLoansToAllLoansExcludingAccruedInterestOriginatedMoreThanFiveYearsBeforeCurrentFiscalYear',
       'FinancingReceivableRatioOfNonperformingLoansToAllLoansExcludingAccruedInterestYearFiveOriginatedFourYearsBeforeCurrentFiscalYear',
       'FinancingReceivableRatioOfNonperformingLoansToAllLoansExcludingAccruedInterestYearFourOriginatedThreeYearsBeforeCurrentFiscalYear',
       'FinancingReceivableRatioOfNonperformingLoansToAllLoansExcludingAccruedInterestYearOneOriginatedCurrentFiscalYear',
       'FinancingReceivableRatioOfNonperformingLoansToAllLoansExcludingAccruedInterestYearThreeOriginatedTwoYearsBeforeCurrentFiscalYear',
       'FinancingReceivableRatioOfNonperformingLoansToAllLoansExcludingAccruedInterestYearTwoOriginatedFiscalYearBeforeCurrentFiscalYear',
       'DisposalGroupIncludingDiscontinuedOperationLongTermDebtNetCurrent',
       'RegulatoryAssetsEarlyRetirementOfGenerationFacilitiesAndTransmissionAssetsCurrent',
       'RegulatoryAssetsEarlyRetirementOfGenerationFacilitiesAndTransmissionAssetsNonCurrent',
       'RegulatoryAssetsStormRestorationCostsCurrent',
       'DisposalGroupIncludingDiscontinuedOperationCurrentMaturitiesOfLongTermDebt',
       'ConsiderationPaidToCustomersCurrent',
       'ConsiderationPaidToCustomersNonCurrent',
       'ConsiderationReceivedFromVendorsCurrent',
       'ConsiderationReceivedFromVendorsNonCurrent',
       'DisposalGroupIncludingDiscontinuedOperationFinanceLeaseObligationsNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationDeferredRevenueNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationEmployeeRelatedLiabilitiesCurrent',
       'DisposalGroupIncludingDiscontinuedOperationOperatingLeaseLiabilityCurrent',
       'AdditionalLiabilityLongDurationInsuranceCurrentWeightedAverageDiscountRate',
       'DisposalGroupIncludingDiscontinuedOperationCurrentPortionOfLongTermDebt',
       'DisposalGroupIncludingDiscontinuedOperationLeaseLiabilitiesNoncurrent',
       'DisposalGroupIncludingDisontinuedOperationOperatingLeaseLiabilityCurrent',
       'DisposalGroupIncludingDiscontinuedOperationAccruedEmployeeCompensationAndBenefitsCurrent',
       'DisposalGroupIncludingDiscontinuedOperationConstructionAdvancesCurrent',
       'DisposalGroupIncludingDiscontinuedOperationFinancingLeaseLiabilitiesNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationOperatingLeaseRightOfUseAssetsNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationOtherIntangibleAssetsNoncurrent',
       'RestrictedCashOtherCurrentAssetsDisposalGroupIncludingContinuedOperations',
       'CurrentWeightedAverageLoanToValueRatioOfCommercialMortgageLoan',
       'DisposalGroupIncludingDiscontinuedOperationRightOfUseLeaseAssetsNoncurrent',
       'BusinessCombinationContingentConsiderationNoncurrentLiability',
       'DisposalGroupIncludingDiscontinuedOperationBridgeLoanCurrent',
       'DisposalGroupIncludingDiscontinuedOperationOperatingLeaseLiabilityNonCurrent',
       'DisposalGroupIncludingDiscontinuedOperationOperatingLeaseRightOfUseAssetsCurrent',
       'ContingentConsiderationPayableCurrent',
       'ProceedsFromDisposalOfNoncurrentAssetsOrDisposalGroupsClassifiedAsHeldForSaleAndDiscontinuedOperations',
       'GainsLossesOnNoncurrentAssetsHeldForSaleNotClassifiedAsDiscontinuedOperations',
       'GainsLossesOnNonCurrentAssetsHeldForSaleNotClassifiedAsDiscontinuedOperations',
       'CurrentFederalTaxExpenseBenefitDiscontinuedOperations',
       'CurrentForeignTaxExpenseBenefitDiscontinuedOperations',
       'CurrentIncomeTaxExpenseBenefitDiscontinuedOperations',
       'CurrentStateAndLocalTaxExpenseBenefitDiscontinuedOperations',
       'DisposalGroupImpairmentLossIncludingDiscontinuedOperationAssetsNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationContractWithCustomerLiabilityCurrent',
       'NetClaimsAndClaimsExpenseRatioCurrentYear',
       'DisposalGroupIncludingDiscontinuedOperationAssetsHeldForSaleCurrent',
       'DisposalGroupIncludingDiscontinuedOperationAssetsHeldForSaleNonCurrent',
       'DisposalGroupIncludingDiscontinuedOperationLiabilityHeldForSaleCurrent',
       'DisposalGroupIncludingDiscontinuedOperationLiabilityHeldForSaleNonCurrent',
       'DeferredConsiderationCurrent',
       'AccruedCollaborationLiabilityCurrent',
       'DisposalGroupIncludingDiscontinuedOperationIntangibleAndOtherNonCurrentAssetsNet',
       'BusinessCombinationProvisionalInformationInitialAccountingIncompleteAdjustmentContingentConsiderationLiabilityAccruedLicensorPaymentCurrent',
       'BusinessCombinationProvisionalInformationInitialAccountingIncompleteAdjustmentContingentConsiderationLiabilityAccruedLicensorPaymentNoncurrent',
       'BusinessCombinationRecognizedIdentifiableAssetsAcquiredAndLiabilitiesAssumedContingentConsiderationLiabilityAccruedLicensorPaymentCurrent',
       'BusinessCombinationRecognizedIdentifiableAssetsAcquiredAndLiabilitiesAssumedContingentConsiderationLiabilityAccruedLicensorPaymentNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationPropertyPlantAndEquipmentNoncurrentGross',
       'DisposalGroupIncludingDiscontinuedOperationRestrictedCashCurrent',
       'DisposalGroupIncludingDiscontinuedOperationRestrictedCashNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationLongTermDebtCurrent',
       'DisposalGroupIncludingDiscontinuedOperationPropertyPlantAndEquipmentNonUtilityPlantNetNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationCurrentMaturitiesOfDebtAndOtherObligations',
       'DisposalGroupIncludingDiscontinuedOperationContingenciesCurrent',
       'DisposalGroupIncludingDiscontinuedOperationContingentPurchaseConsiderationsCurrent',
       'DisposalGroupIncludingDiscontinuedOperationCustomerRefundLiabilityCurrent',
       'DisposalGroupIncludingDiscontinuedOperationLongTermDebtAndCapitalLeaseObligationsExcludingCurrentPortionNet',
       'MinimumCurrentRatioPerCreditFacility',
       'DiscontinuedOperationCurrentIncomeTaxExpenseBenefit',
       'DisposalGroupIncludingDiscontinuedOperationInventoryNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationLinefillNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationOperatingLeaseRightOfUseAssetsNetNoncurrent',
       'DescriptionOfCapitalAdequacyRatioInCurrentEstimateOfValueInUse',
       'DescriptionOfCostIncomeRatioUsedInCurrentEstimateOfValueInUse',
       'DescriptionOfOperatingIncomeRatioUsedInCurrentEstimateOfValueInUse',
       'DescriptionOfTier1CapitalAdequacyRatioInCurrentEstimateOfValueInUse',
       'AssetAcquisitionContingentConsiderationLiabilityNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationsUnfavorableContractLiabilityCurrent',
       'DebtInstrumentCovenantComplianceCurrentRatio',
       'DisposalGroupIncludingDiscontinuedOperationIntangibleAssetsNotSubjectToAmortizationNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationIntangibleAssetsSubjectToAmortizationNoncurrent',
       'BusinessCombinationRecognizedIdentifiableAssetsAcquiredAndLiabilitiesAssumedCurrentAssetsOfDiscontinuedOperations',
       'BusinessCombinationRecognizedIdentifiableAssetsAcquiredAndLiabilitiesAssumedCurrentLiabilitiesOfDiscontinuedOperations',
       'DisposalGroupIncludingDiscontinuedOperationContractWithCustomerReceivableAfterAllowanceForCreditLossCurrent',
       'DisposalGroupIncludingDiscontinuedOperationGrossProvedPropertiesNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationGrossUnprovedPropertiesNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationLeaseLiabilitiesCurrent',
       'DisposalGroupIncludingDiscontinuedOperationOperatingLeasesRightOfUseAssetsNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationPropertyPlantAndEquipmentOtherGrossNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationRevenueDistributionsPayableCurrent',
       'ProceedsFromDisposalOfNoncurrentAssetsOrDisposalGroupsClassifiedAsHeldForSaleAndDiscontinuedOperationsNet',
       'DisposalGroupIncludingDiscontinuedOperationsDeferredTaxAssetsNoncurrent',
       'ContingentConsiderationAndCompensationLiabilitiesNonCurrent',
       'ContingentConsiderationCurrent',
       'ContingentConsiderationNoncurrent',
       'CurrentContractLiabilitiesForCollaborationRevenue',
       'AccruedCollaborationExpensesCurrent',
       'PercentageOfOtherAccruedLiabilitiesConcentrationRiskPercentageToTotalCurrentLiabilities',
       'DiscontinuedOperationCurrentFederalTaxExpenseBenefit',
       'DiscontinuedOperationCurrentIncomeTaxExpenseBenefitTotal',
       'DiscontinuedOperationCurrentStateAndLocalTaxExpenseBenefit',
       'FinancialCovenantsCurrentAssetsToCurrentLiabilitiesRatio',
       'SupportAgreementCovenantNumberOfTrailingFiscalQuartersAddedToCurrentQuarterForCalculationOfConsolidatedFixedChargesCoverageRatio',
       'AssetAcquisitionContingentConsiderationLiabilityCurrent',
       'ContingentConsiderationCurrentPortion',
       'ContingentConsiderationNonCurrent',
       'ContingentConsiderationReceivableCurrent',
       'CurrentAndNonCurrentLeaseLiabilitiesThroughAcquisitionsApplyingTheOptionalConcentrationTest',
       'CurrentRefundsProvisionDiscontinuedOperations',
       'NonCurrentFinancialAndOtherAssetsThroughAcquisitionsApplyingTheOptionalConcentrationTest',
       'OtherCurrentAssetsRecognisedAsOfAcquisitionDateThroughAcquisitionsApplyingTheOptionalConcentrationTest',
       'DebtInstrumentCovenantLeverageRatioCurrentMinimum',
       'DisposalGroupIncludingDiscontinuedOperationsContractWithCustomerAssetCurrent',
       'DisposalGroupIncludingDiscontinuedOperationsCustomerDepositsCurrent',
       'DisposalGroupIncludingDiscontinuedOperationShortTermBorrowingsCurrent',
       'DisposalGroupIncludingDiscontinuedOperationsMaterialsAndSuppliesCurrent',
       'DisposalGroupIncludingDiscontinuedOperationsRegulatoryAssetsCurrent',
       'DisposalGroupIncludingDiscontinuedOperationsRegulatoryLiabilitiesCurrent',
       'TransitionAndSystemRestorationBondsLongTermDebtCurrent',
       'TransitionAndSystemRestorationBondsLongTermDebtNonCurrent',
       'DisposalGroupIncludingDiscontinuedOperationIntangibleAssetsNoncurrentAccumulatedAmortization',
       'DisposalGroupIncludingDiscontinuedOperationRightofUseAssetsCurrent',
       'ContingentConsiderationRecognisedAsOfAcquisitionDateCurrent',
       'DisposalGroupIncludingDiscontinuedOperationOperatingLeasesCurrentMaturities',
       'CurrentContingentConsiderationLiabilities',
       'NonCurrentContingentConsiderationLiabilities',
       'DisposalGroupNotIncludingDiscontinuedOperationLiabilitiesCurrent',
       'DisposalGroupNotIncludingDiscontinuedOperationLiabilitiesNoncurrent',
       'BusinessCombinationConsiderationTransferredLiabilitiesIncurredCurrentPortion',
       'BusinessCombinationConsiderationTransferredLiabilitiesIncurredNonCurrentPortion',
       'CurrentDeferredConsideration', 'NonCurrentDeferredConsideration',
       'CurrentRatio',
       'DisposalGroupIncludingDiscontinuedOperationLeaseObligationsCurrent',
       'DisposalGroupIncludingDiscontinuedOperationLeaseObligationsNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationAccruedExpenseAccruedIncomeTaxesAndOtherLiabilitiesCurrent',
       'DeferredRevenueConsiderationReceivedInAdvanceOfServicesPerformedNetOfRevenueRecognizedInCurrent',
       'SettlementAssetsIncludingDiscontinuedOperationsCurrent',
       'SettlementLiabilitiesIncludingDiscontinuedOperationsCurrent',
       'DisposalGroupIncludingDiscontinuedOperationDerivativeInstrumentsCurrent',
       'DisposalGroupIncludingDiscontinuedOperationDerivativeInstrumentsLiabilitiesCurrent',
       'DisposalGroupIncludingDiscontinuedOperationRegulatoryAssetsCurrent',
       'DisposalGroupIncludingDiscontinuedOperationRegulatoryAssetsNoncurrent',
       'DisposalGroupIncludingDiscontinuedOperationRegulatoryLiabilitiesCurrent',
       'DisposalGroupIncludingDiscontinuedOperationRegulatoryLiabilitiesNoncurrent',
       'AccruedContingentConsiderationsAndEarn-OutsCurrent',
       'ContingentConsiderationLiabilityCurrent',
       'ContingentConsiderationLiabilityNoncurrent',
       'ReceivableFromCollaborationAgreementCurrent',
       'BusinessCombinationContingentConsiderationOtherLiabilityCurrent',
       'BusinessCombinationContingentConsiderationOtherLiabilityNonCurrent',
       'PreExchangeListingAdministrationFeesAsAPercentageOfTheAverageInvestmentsForTheCurrentAndThePreceedingQuarter',
       'IncomeTaxExpenseBenefitContinuingOperationsCurrent',
       'DebtCovenantCurrentRatio',
       'DisposalGroupIncludingDiscontinuedOperationCurrentPortionOfOtherBorrowings',
       'DebtInstrumentCovenantCurrentRatio', 'ProFormaCurrentRatio',
       'BusinessCombinationContingentConsiderationLiabilityAndDeferredConsiderationCurrent',
       'BusinessCombinationContingentConsiderationLiabilityAndDeferredConsiderationNoncurrent',
       'BusinessCombinationDeferredConsiderationCurrent',
       'CurrentLiabilitiesFromContinuingOperations',
       'CurrentLiabilitiesFromDiscontinuedOperations',
       'OtherLiabilitiesCurrentDiscontinuedOperations',

In [40]:
# Define the tags you want to check
Current_Ratio_tags = [
    'CurrentRatio',
    'DebtServiceCoverageRatioCurrentFiscalYear',
    'DebtInstrumentCovenantComplianceCurrentRatio',
    'DebtInstrumentCovenantCurrentRatio',
    'MinimumCurrentRatioPerCreditFacility ',
    'MinimumCurrentRatioRequired',
    'DebtCovenantCurrentRatio',
    'LineOfCreditFacilityCovenantTermsMinimumCurrentRatio',
    'DebtInstrumentCovenantCurrentRatioMinimum',
    'FinancialCovenantsCurrentAssetsToCurrentLiabilitiesRatio',
    'DebtInstrumentCovenantComplianceCurrentRatio' 
]

# Count occurrences for each tag
for tag in Current_Ratio_tags:
    count = (joinedFactsAndSubmissionsAnnual['tag'] == tag).sum()
    if count > 0:
        print(f"{tag}: {count} times")
    else:
        print(f"{tag}: NOT FOUND")

CurrentRatio: 2 times
DebtServiceCoverageRatioCurrentFiscalYear: 6 times
DebtInstrumentCovenantComplianceCurrentRatio: 2 times
DebtInstrumentCovenantCurrentRatio: 3 times
MinimumCurrentRatioPerCreditFacility : NOT FOUND
MinimumCurrentRatioRequired: 1 times
DebtCovenantCurrentRatio: 1 times
LineOfCreditFacilityCovenantTermsMinimumCurrentRatio: 1 times
DebtInstrumentCovenantCurrentRatioMinimum: 1 times
FinancialCovenantsCurrentAssetsToCurrentLiabilitiesRatio: 1 times
DebtInstrumentCovenantComplianceCurrentRatio: 2 times

In [41]:
filtered_data1 = joinedFactsAndSubmissionsAnnual[joinedFactsAndSubmissionsAnnual['tag'].isin(Current_Ratio_tags)]
filtered_data = pd.concat([filtered_data, filtered_data1], ignore_index=True)
filtered_data

,adsh,tag,ddate,qtrs,value,footnote,cik,name,sic,form
0,0000004281-26-000012,DebtInstrumentCovenantComplianceRatioOfConsoli...,20230731,0,3.7500,,4281,HOWMET AEROSPACE INC.,3350,10-K
1,0000004281-26-000012,DebtInstrumentCovenantComplianceRatioOfConsoli...,20251231,4,3.7500,,4281,HOWMET AEROSPACE INC.,3350,10-K
2,0000058492-26-000107,RatioOfIndebtednessToEBITDA,20251231,0,3.5000,,58492,LEGGETT & PLATT INC,2510,10-K
3,0000058492-26-000107,RatioOfIndebtednessToEBITDA,20251231,0,4.0000,,58492,LEGGETT & PLATT INC,2510,10-K
4,0000093389-26-000012,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20251231,0,1.0000,,93389,"STANDARD MOTOR PRODUCTS, INC.",3714,10-K
...,...,...,...,...,...,...,...,...,...,...
124,0001520006-26-000002,LineOfCreditFacilityCovenantTermsMinimumCurren...,20251231,4,1.0000,,1520006,MATADOR RESOURCES CO,1311,10-K
125,0001621434-26-000018,CurrentRatio,20251231,4,1.0000,,1621434,"BLACK STONE MINERALS, L.P.",1311,10-K
126,0001658566-26-000035,DebtInstrumentCovenantComplianceCurrentRatio,20251231,4,1.0000,,1658566,PERMIAN RESOURCES CORP,1311,10-K
127,0001698990-26-000005,DebtInstrumentCovenantCurrentRatio,20241031,0,1.0000,,1698990,MAGNOLIA OIL & GAS CORP,1311,10-K
128,0001891027-26-000019,DebtInstrumentCovenantCurrentRatioMinimum,20250430,0,1.3500,,1891027,"MNTN, INC.",7310,10-K

In [42]:
Operating_Cash_Flow_to_Total_Debt  = joinedFactsAndSubmissionsAnnual[
    joinedFactsAndSubmissionsAnnual['tag'].str.contains('Operating', case=False, na=False) &
    joinedFactsAndSubmissionsAnnual['tag'].str.contains('Cash', case=False, na=False)&
    joinedFactsAndSubmissionsAnnual['tag'].str.contains('Flow', case=False, na=False)&
    joinedFactsAndSubmissionsAnnual['tag'].str.contains('Debt', case=False, na=False)



]
Operating_Cash_Flow_to_Total_Debt['tag'].unique()

array(['NetDebtToOperatingCashFlowMaximumRatio',
       'RatioOfNetDebtToOperatingCashFlow'], dtype=object)

In [43]:
# Define the tags you want to check
Operating_Cash_Flow_to_Total_Debt_tags = [
    'NetDebtToOperatingCashFlowMaximumRatio',
       'RatioOfNetDebtToOperatingCashFlow']

# Count occurrences for each tag
for tag in Operating_Cash_Flow_to_Total_Debt_tags:
    count = (joinedFactsAndSubmissionsAnnual['tag'] == tag).sum()
    if count > 0:
        print(f"{tag}: {count} times")
    else:
        print(f"{tag}: NOT FOUND")

NetDebtToOperatingCashFlowMaximumRatio: 1 times
RatioOfNetDebtToOperatingCashFlow: 1 times

In [44]:
filtered_data1 = joinedFactsAndSubmissionsAnnual[joinedFactsAndSubmissionsAnnual['tag'].isin(Operating_Cash_Flow_to_Total_Debt_tags)]
filtered_data = pd.concat([filtered_data, filtered_data1], ignore_index=True)
filtered_data

,adsh,tag,ddate,qtrs,value,footnote,cik,name,sic,form
0,0000004281-26-000012,DebtInstrumentCovenantComplianceRatioOfConsoli...,20230731,0,3.7500,,4281,HOWMET AEROSPACE INC.,3350,10-K
1,0000004281-26-000012,DebtInstrumentCovenantComplianceRatioOfConsoli...,20251231,4,3.7500,,4281,HOWMET AEROSPACE INC.,3350,10-K
2,0000058492-26-000107,RatioOfIndebtednessToEBITDA,20251231,0,3.5000,,58492,LEGGETT & PLATT INC,2510,10-K
3,0000058492-26-000107,RatioOfIndebtednessToEBITDA,20251231,0,4.0000,,58492,LEGGETT & PLATT INC,2510,10-K
4,0000093389-26-000012,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20251231,0,1.0000,,93389,"STANDARD MOTOR PRODUCTS, INC.",3714,10-K
...,...,...,...,...,...,...,...,...,...,...
126,0001658566-26-000035,DebtInstrumentCovenantComplianceCurrentRatio,20251231,4,1.0000,,1658566,PERMIAN RESOURCES CORP,1311,10-K
127,0001698990-26-000005,DebtInstrumentCovenantCurrentRatio,20241031,0,1.0000,,1698990,MAGNOLIA OIL & GAS CORP,1311,10-K
128,0001891027-26-000019,DebtInstrumentCovenantCurrentRatioMinimum,20250430,0,1.3500,,1891027,"MNTN, INC.",7310,10-K
129,0001104659-26-013854,NetDebtToOperatingCashFlowMaximumRatio,20251231,4,4.2500,,868675,TELUS CORP,4812,40-F
130,0001104659-26-013854,RatioOfNetDebtToOperatingCashFlow,20251231,4,4.2500,,868675,TELUS CORP,4812,40-F

In [45]:
Debt_To_Equity = joinedFactsAndSubmissionsAnnual[
    joinedFactsAndSubmissionsAnnual['tag'].str.contains('Debt', case=False, na=False) &
    joinedFactsAndSubmissionsAnnual['tag'].str.contains('Equity', case=False, na=False)
]
Debt_To_Equity['tag'].unique()

array(['DebtAndEquitySecuritiesAvailableForSale',
       'DebtAndEquitySecuritiesAvailableForSaleAmortizedCost',
       'DebtAndEquitySecuritiesUnrealizedGain',
       'DebtAndEquitySecuritiesUnrealizedLoss',
       'DebtInstrumentCovenantCommonEquityTierOneRatio',
       'DebtInstrumentRepurchaseReductionToEquity',
       'DebtAndEquitySecuritiesUnrealizedGainLoss',
       'DebtAndEquitySecuritiesGainLoss',
       'LimitedPartnershipsInvestedInPrivateDebtAndEquity',
       'PercentageOfLimitedPartnershipsInvestedInPrivateDebtAndEquity',
       'Proceedsfromsalesandmaturitiesofavailableforsaledebtequityandothersecurities',
       'EquityMethodInvestmentSummarizedFinancialInformationDebt',
       'CapitalizationLongtermDebtAndEquity',
       'DebtSecuritiesTradingAndEquitySecuritiesFvNiCost',
       'DebtAndEquitySecuritiesRealizedGainLoss',
       'DebtAndEquitySecuritiesRealizedGain',
       'DebtAndEquitySecuritiesRealizedLoss',
       'PaymentsToAcquireDebtSecuritiesAvailableForSaleAndEquitySecuritiesFVNI',
       'ProceedsFromSaleOfDebtSecuritiesAvailableForSaleAndEquitySecurities',
       'PercentageOfCarryingValueOfInvestmentsInPrivateDebtAndEquity',
       'FERCPercentDebtinProposedCommonEquityRatio',
       'PercentDebtinProposedCommonEquityRatio',
       'EffectiveIncomeTaxRateReconciliationDebtForEquityExchange',
       'EffectiveIncomeTaxRateReconciliationDebtForEquityExchangePercent',
       'NoncashOrPartNoncashDivestitureDebtForEquityExchange',
       'CapitalizationShortTermDebtLongTermDebtAndEquity',
       'EquityToTotalCapitalizationRatioExcludingShort-TermDebt',
       'EquityToTotalCapitalizationRatioExcludingShort-TermDebtHighEndOfRange',
       'EquityToTotalCapitalizationRatioExcludingShort-TermDebtLowEndOfRange',
       'DebtInstrumentConvertibleNumberOfEquityInstruments',
       'DebtSecuritiesAvailableForSaleCreditLossesRecognizedInEarningsForThePeriodAsPercentageOfShareholdersEquityOnAfterTaxBasis',
       'DebtConversionConvertedToEquityInstrumentFairValueAdjustment',
       'EquityUnitsPercentageInterestInAttachedDebtInstrument',
       'InvestmentsInDebtAndEquitySecurities',
       'DebtSecuritiesAvailableForSaleAndEquitySecuritiesFVNI',
       'DebtSecuritiesAvailableForSaleAndEquitySecuritiesFVNICost',
       'DebtForEquityExchangeLossOnSharesExchanged',
       'DebtForEquityExchangeSharesExchanged',
       'DebtAndEquitySecuritiesRealizedGains',
       'DebtAndEquitySecuritiesRealizedLosses',
       'DebtSecuritiesandEquitySecuritiesFVNI',
       'DebtInstrumentRedemptionPricePercentOfNetCashProceedsFromEquityOffering',
       'DebtInstrumentIssuanceRightTriggerThresholdEquityAttributableToParentExcludingAccumulatedOtherComprehensiveIncomeLoss',
       'DebtSecuritiesAvailableForSaleAndEquitySecuritiesFVNIAccumulatedGrossUnrealizedGainBeforeTax',
       'DebtSecuritiesAvailableForSaleAndEquitySecuritiesFVNIAccumulatedGrossUnrealizedLossBeforeTax',
       'ProceedsFromSaleOfDebtSecuritiesAvailableForSaleAndEquityMethodInvestments',
       'EquityMethodInvestmentDebtForgiveness',
       'DebtInstrumentCovenantDebtToAllowanceAndEquityRatioMaximum',
       'DebtInstrumentCovenantDebtToEquityRatioMaximum',
       'DebtInstrumentPreferredEquityRedeemedAmount',
       'DebtInstrumentCollateralPercentageOfEquityInterestInCertainForeignSubsidiaries',
       'PaymentsToAcquireAvailableForSaleSecuritiesDebtAndEquitySecurities',
       'OtherCashPaymentsToAcquireEquityOrDebtInstrumentsOfOtherEntitiesClassifiedAsInvestingActivities',
       'IncomeLossFromEquityMethodInvestmentsAllocableToDepreciationAmortizationInterestExpenseAndGainLossOnDebtExtinguishment',
       'DebtSecuritiesAvailableForSaleAndEquitySecuritiesFvNi',
       'DebtSecuritiesAvailableForSaleAndEquitySecuritiesFvNiCost',
       'DebtSecuritiesAvailableForSaleAndEquitySecuritiesFvNiGrossUnrealizedGain',
       'DebtSecuritiesAvailableForSaleAndEquitySecuritiesFvNiGrossUnrealizedLoss',
       'CashEquivalentsDebtAndEquitySecuritiesCost',
       'CashEquivalentsDebtAndEquitySecuritiesFairValue',
       'CashEquivalentsDebtAndEquitySecuritiesUnrealizedGain',
       'CashEquivalentsDebtAndEquitySecuritiesUnrealizedLoss',
       'DebtAndEquitySecuritiesCost', 'DebtAndEquitySecuritiesFairValue',
       'DebtInstrumentConvertibleNumberOfEquityInstrumentsIfDebtConverted',
       'NonCurrentDebtAndEquityInstrumentsHeld',
       'TargetedMaximumDebtToEquityRatio',
       'ThirdPartyDebtSecuritiesAndEquityInstrumentsHeldInCustody',
       'EquityMethodInvestmentDebtOfPartiallyOwnedEntities',
       'EquityMethodInvestmentProRataShareDebtOfPartiallyOwnedEntities',
       'DebtSecuritiesAvailableForSaleExcludingInterestAndEquitySecuritiesCurrent',
       'PaymentsToAcquireOtherDebtAndEquityInvestments',
       'DebtAndEquitySecuritiesFairValueGains',
       'DebtAndEquitySecuritiesFairValueLosses',
       'LineOfCreditFacilityDebtCovenantRepurchaseOfEquitySecurities',
       'DebtEquityMarketableAndOtherSecuritiesAvailableForSale',
       'DebtEquityMarketableAndOtherSecuritiesAvailableForSaleAmortizedCost',
       'DebtEquityMarketableAndOtherSecuritiesAvailableForSaleUnrealizedGain',
       'DebtEquityMarketableAndOtherSecuritiesAvailableForSaleUnrealizedLoss',
       'DebtSecuritiesAndEquitySecuritiesFVNI',
       'ConversionOfDebtSecurityToEquitySecurity',
       'DebtAndEquitySecuritiesRealizedGainLossSalesProceeds',
       'DebtandEquitySecuritiesRealizedGains',
       'DebtandEquitySecuritiesRealizedLosses',
       'DebtInstrumentConvertibleNumberOfEquityInstrumentsConversionRatePer1000InPrincipal',
       'EquityMethodInvestmentDebtCovenantLiabilityCapPercent',
       'EquityMethodInvestmentSummarizedFinancialInformationMortgageIndebtedness',
       'InterestIncomeCommercialRealEstateDebtAndPreferredEquity',
       'DebtSecuritiesAvailableForSaleAmortizedCostAndEquitySecuritiesFV',
       'DebtAndEquitySecurities',
       'DebtInstrumentCovenantPercentageOfNetCashProceedsOfFutureEquityIssuances',
       'NumberOfOtherEquityInstrumentsIssuedForDebtSettlementInSharebasedPaymentArrangement',
       'WeightedAverageExercisePriceOfOtherEquityInstrumentsIssuedForDebtSettlementInSharebasedPaymentArrangement',
       'InvestmentsDebtSecuritiesEquityMethodInvestmentsAndOtherAmortizedCost',
       'InvestmentsDebtSecuritiesEquitySecuritiesAndOtherFairValue',
       'DebtInstrumentPercentageOfEquityInterestAsCollateralGuarantee',
       'DebtInstrumentEquityComponent',
       'AdjustmentsToAdditionalPaidInCapitalEquityComponentOfConvertibleDebt',
       'AdjustmentsToAdditionalPaidInCapitalTaxBenefitFromEquityComponentOfConvertibleDebt',
       'DebtSecuritiesAvailableForSaleExcludingAccruedInterestAndEquitySecurities',
       'DebtInstrumentConvertibleCarryingAmountOfTheEquityComponent',
       'EquityMethodInvestmentDifferenceBetweenCarryingAmountAndUnderlyingEquityDebt',
       'EquityMethodInvestmentProRataShareOfDebtObligationsOfJointVenture',
       'CapitalizedAmountOfEquityAndDebt', 'NetDebtEquityCreditDeduction',
       'AuditorsRemunerationForWorkPerformedAsReportingAccountantsOnDebtAndEquityIssuances',
       'ProceedsFromMaturitiesRepaymentsAndCallsOfDebtSecuritiesAvailableForSaleAndEquitySecuritiesFvNi',
       'ProceedsFromSaleOfDebtSecuritiesAvailableForSaleAndEquitySecuritiesFvNi',
       'EquityInvestmentsAndConvertibleDebtSecurities',
       'MarketableEquityInvestmentsAndConvertibleDebtSecuritiesPurchases',
       'MarketableEquityInvestmentsAndConvertibleDebtSecuritiesRealizedGainLoss',
       'MarketableEquityInvestmentsAndConvertibleDebtSecuritiesUnrealizedGainLoss',
       'MarketableEquityInvestmentsAndConvertibleDebtSecuritiesUnrealizedGainLossForeignCurrencyTransaction',
       'ProceedsFromSaleAndRedemptionOfMarketableEquityInvestmentsAndConvertibleDebtSecurities',
       'CashAndNonCashProceedsFromDivestituresAndSaleOfDebtSecuritiesAndEquityInvestments',
       'OtherCashReceiptsFromSalesOfEquityOrDebtInstrumentsOfOtherEntitiesClassifiedAsInvestingActivities',
       'AccumulatedGrossUnrealizedGainLossBeforeTaxAvailableForSaleDebtSecuritiesAndEquitySecurities',
       'TotalFinancialDebtPercentageOfTotalEquityAndLiabilities',
       'TotalFinancialDebtPercentageOfTotalEquityAndLiabilitiesIncreaseDecreaseFromPriorPeriod',
       'DebtCovenantRatioOfDebtToDebtPlusEquity',
       'PercentageOfTotalDebtAndLeaseLiabilitiesToTotalDebtAndLeaseLiabilitiesPlusShareholdersEquity',
       'PrivateDebtAndEquityPercentageContributedToFairValueOfPlanAssets',
       'RatioOfDebtToDebtPlusEquity', 'DebtAndEquitySecuritiesImpairment',
       'DebtInstrumentCovenantMilestoneEquityMethodInvestmentPercentageForGuarantee',
       'DebtInstrumentConvertibleEquityComponentInterestAccrued',
       'AdjustmentsToAdditionalPaidInCapitalEquityComponentOfConvertibleDebtSubsequentAdjustmentsShares',
       'AdjustmentsToAdditionalPaidInCapitalEquityComponentOfConvertibleDebtSubsequentAdjustmentsValue',
       'DebtInstrumentCovenantNetCashProceedsOfAdditionalEquityIssuancesAmount',
       'LineOfCreditFacilityCovenantTermsMaximumDebtToEquityPercentage',
       'EquityMethodInvestmentSummarizedFinancialInformationThirdPartyDebt',
       'ConversionOfDebtToEquityConversionPrice',
       'PercentageOfConversionOfDebtToEquity', 'DebtToEquityRatio',
       'DebtInstrumentRedemptionPricePercentageNetOfCashProceedsOfEquityOfferings',
       'DebtInstrumentRedemptionPricePercentageWithEquityOfferings',
       'AdjustmentsToAdditionalPaidInCapitalEquityComponentOfConvertibleDebtSubsequentAdjustments',
       'AvailableForSaleDebtAndEquitySecuritiesCurrent',
       'AvailableForSaleDebtAndEquitySecuritiesNonCurrent',
       'PaymentsToAcquireAvailableForSaleSecuritiesDebtAndEquity',
       'MaximumPercentageOfAggregatePrincipalAmountOfDebtRedeemableByPartnershipWithEquityOfferings',
       'DebtAndEquityInstrumentFairValuePerUnit',
       'NetProceedsFromIssuanceOfDebtAndEquity',
       'ProceedsFromIssuanceOfDebtAndEquityGross',
       'AvailableForSaleDebtSecuritiesAndEquitySecuritiesFvNi',
       'AvailableForSaleDebtSecuritiesAndEquitySecuritiesFvNiAccumulatedGrossUnrealizedGainBeforeTaxes',
       'AvailableForSaleDebtSecuritiesAndEquitySecuritiesFvNiAccumulatedGrossUnrealizedLossBeforeTaxes',
       'AvailableForSaleDebtSecuritiesAndEquitySecuritiesFvNiAmortizedCostBasis',
       'DebtInstrumentCovenantTermsRequiredParentCompanyOwnershipOfOutstandingVotingEquityInterestInSubsidiary',
       'EquityMethodInvestmentSummarizedFinancialInformationLongTermDebt',
       'LineofCreditFacilityCovenantTermsMaximumDebttoEquityRatio',
       'RegulatoryRestrictionsMaximumDebttoEquity',
       'IncomeTaxReconciliationInterestDeductionOnEquityIssuedConvertibleDebt',
       'NetDebtAndShareholdersEquity',
       'TransactionCostsRelatedToIssueOfEquitySecuritiesOrConvertibleDebtSecurities',
       'DebtAndEquitySecuritiesReceivedForCertainObligationsRealEstateAndRevenue',
       'NonCashRevenueFromDebtAndEquitySecuritiesReceived',
       'DebtAndEquitySecuritiesRealizedGainLossOnForeignCurrencyTransactions',
       'DebtAndEquitySecuritiesUnrealizedGainLossOnForeignCurrencyTransactions',
       'DebtAndEquitySecuritiesUnrealizedGainLossOnInterestRateSwapAttributedToUnsecuredNotes',
       'DebtAndEquitySecuritiesUnrealizedGainLossOnInvestments',
       'DebtAndEquitySecuritiesAndDerivativeInstrumentsRealizedGainLossExcludingCreditLoss',
       'NonCashDebtAndEquitySecuritiesAndDerivativeInstrumentsRealizedGainLossExcludingCreditLoss',
       'DebtEquityRatio',
       'DebtAndEquitySecuritiesAndForeignCurrencyTransactionPriceChangeRealizedGainLossOperatingBeforeTax',
       'EquityMethodInvestmentDebtCapitalContribution',
       'EquityAndDebtAvailableForSaleSecurities',
       'AvailableForSaleDebtSecuritiesAndEquityTradingSecuritiesGrossUnrealizedLosses',
       'AvailableForSaleSecuritiesDebtEquitySecuritiesAndTradingSecurities',
       'AvailableForSaleSecuritiesDebtEquitySecuritiesAndTradingSecuritiesAmortizedCostBasis',
       'AvailableForSaleSecuritiesDebtEquitySecuritiesAndTradingSecuritiesUnrealizedGainBeforeTax',
       'AvailableForSaleSecuritiesDebtEquitySecuritiesAndTradingSecuritiesUnrealizedLossBeforeTax',
       'DebtAndEquitySecuritiesAvailableForSaleRealizedGain',
       'DebtAndEquitySecuritiesAvailableForSaleRealizedLoss',
       'DebtAndEquitySecuritiesGainLossNet',
       'AvailableForSaleSecuritiesDebtSecuritiesAndEquitySecuritiesFvNi',
       'DebtInstrumentCovenantRequiredMinimumNetWorthComponentTwoPercentOfNetEquityProceedsReceivedFromIssuanceAndSaleOfEquityInterests',
       'DebtandEquitySecuritiesAvailableforsale',
       'IncomeLossFromContinuingOperationsBeforeEquityMethodInvestmentsExtinguishmentOfDebtGainOnRealEstateIncomeTaxesNoncontrollingInterest',
       'DeferredTaxLiabilitiesUnrealizedGainOnDebtAndEquitySecurities',
       'DebtSecuritiesAvailableForSaleAndEquitySecurities',
       'DebtCovenantNetCashToEquityMultipleThreshold',
       'InvestmentCompanyDebtToEquityLeverageRatio',
       'DebtInstrumentCovenantEquityCapitalToTotalAssetsMinimumPercent',
       'DebtInstrumentCovenantMinimumEquityCapitalAmount',
       'EquitySecuritiesFVNIAndDebtSecuritiesAvailableForSaleExcludingAccruedInterestNoncurrent',
       'NetUnrealizedGainsLossesOnInvestmentsInEquitySecuritiesAndTradingDebtSecurities',
       'DebtSecuritiesAvailableforsaleandEquitySecuritiesFVNI',
       'DebtSecuritiesAvailableforsaleandEquitySecuritiesFVNIUnrealizedGain',
       'DebtSecuritiesAvailableforsaleandEquitySecuritiesFVNIUnrealizedLoss',
       'DebtAndEquitySecuritiesRealizedGainLossBeforeDistributions',
       'DebtSecuritiesAvailableForSaleHeldToMaturityAndEquitySecuritiesFVNI',
       'DebtSecuritiesAvailableForSaleHeldToMaturityAndEquitySecuritiesFVNIAccumulatedGrossUnrealizedLossBeforeTaxCurrent',
       'DebtSecuritiesAvailableForSaleHeldToMaturityAndEquitySecuritiesFVNICostCurrent',
       'DebtInstrumentPercentageOfEquityInterestOfEntityAndDomesticSubsidiariesOfSubsidiaryGuarantorsPledge',
       'DebtInstrumentPercentageOfEquityInterestOfEntityAndForeignSubsidiariesOfSubsidiaryGuarantorsPledge',
       'DebtInstrumentCovenantPercentOfNewEquityOfferingsMaximum',
       'StockIssuedDuringPeriodSharesUponExchangeOfDebtForEquity',
       'StockIssuedDuringPeriodValueUponExchangeOfDebtForEquity',
       'DebtInstrumentMaturityMinimumNetProceedsFromSaleOfEquityInterests',
       'DebtSecuritiesAvailableforsaleHoldingGreaterThan10PercentOfEquity',
       'ProceedsInjectedIncreaseToEquityCapitalFromIssuanceOfSubordinatedLongtermDebt',
       'AdjustmentsToAdditionalPaidInCapitalEquityComponentOfConvertibleDebtPartialTerminationOfCappedCallOptions',
       'AdjustmentsToAdditionalPaidInCapitalEquityComponentOfConvertibleDebtPurchaseOfCappedCallOption',
       'NetDebtAndEquity',
       'AvailableForSaleDebtSecuritiesAndEquitySecuritiesFVNI',
       'DebtSecuritiesAvailableForSaleAndEquitySecuritiesFVNIAmortizedCost',
       'DebtSecuritiesTradingAndEquitySecuritiesAccumulatedGrossUnrealizedLossBeforeTax',
       'DebtOutstandingAllowablePerDollarOfEquity',
       'DebtInstrumentCollateralEquityInterestsPledgedPercentageOfCapitalStock',
       'EquitySecuritiesFVNIAndWithoutReadilyDeterminableFairValueAndDebtSecuritiesAvailableForSale',
       'DebtRedemptionNumberOfEquityOfferings',
       'AvailableForSaleDebtSecuritiesTradingSecuritiesAndEquitySecurities',
       'MeasurementInputForAvailableForSaleDebtSecuritiesTradingSecuritiesAndEquitySecurities',
       'GainLossOnDebtSecuritiesAndSaleOfEquitySecuritiesWithoutReadilyDeterminableFairValue',
       'DebtInstrumentCovenantComplianceMinimumShareholdersEquityAmount',
       'DebtInstrumentCovenantComplianceShareholdersEquityPercentageOfNetProceedsFromEquityIssuances',
       'AdjustmentsToAdditionalPaidInCapitalEquityComponentOfConvertibleDebtOptionIndexedToIssuersEquity',
       'DebtConversionInducementPaymentEquityConsiderationAmount',
       'DebtConversionInducementPaymentEquityConsiderationSharesIssued',
       'DebtInstrumentCovenantEquityInvestmentRatioMinimum',
       'DebtInstrumentCovenantPercentageOfNetProceedsRaisedInFutureEquityIssuancesUsedForComputingTangibleNetWorthToBeMaintained',
       'AdjustmentsToAdditionalPaidInCapitalEquityComponentOfConvertibleDebtHedges',
       'DebtSecuritiesAvailableForSaleExcludingEquitySecurities',
       'DebtCovenantMaximumJuniorDebtOrEquityPurchasableQuarterly',
       'DebtInstrumentCovenantPercentageOfTangibleEquityToTangibleManagedAssets',
       'DebtInstrumentCovenantComplianceCollateralPledgedSubsidiaryEquityInterestsPercent',
       'DebtSecuritiesEquityAndOtherInvestments',
       'DebtInstrumentNetEquityCapital',
       'DebtInstrumentCovenantNetProceedsRaisedInFutureEquityIssuancesThresholdPercent',
       'MaximumAmountOfVotingEquityInterestInForeignSubsidiariesThatGuaranteeDebtObligation',
       'AdjustmentsToAdditionalPaidInCapitalEquityComponentOfConvertibleDebtAndDerivatives',
       'DebtSecuritiesTradingAndEquitySecuritiesFVNIAccumulatedUnrealizedGainBeforeTax',
       'DebtSecuritiesTradingAndEquitySecuritiesFVNIAccumulatedUnrealizedLossBeforeTax',
       'DebtInstrumentRedemptionPriceMaximumRedemptionFromEquityOfferingPercentage',
       'DebtAndPreferredEquityReserves',
       'ExchangeOfDebtInvestmentForRealEstateOrEquityInJointVenture',
       'OriginationOfDebtAndPreferredEquityInvestments',
       'RepaymentsOrRedemptionOfDebtAndPreferredEquityInvestments',
       'AdjustmentsToAdditionalPaidInCapitalEquityComponentOfConvertibleDebtRetirementOfConvertibleSeniorNotesNet',
       'AdjustmentsToAdditionalPaidInCapitalEquityComponentOfConvertibleDebtSettlementOfCappedCalls',
       'DebtInstrumentCovenantNetWorthMinimumPercentageOfCashProceedsOfEquityIssuance',
       'RegulatoryRateCaseFilingsRequestedAuthorizationForDebtAndEquityIssuanceAmount',
       'DebtAndEquitySecuritiesSoldDuringPeriodCarryingValue',
       'DebtInstrumentCovenantTangibleNetWorthPercentageOfIncreaseInEquity',
       'ConversionOfAvailableForSaleDebtSecuritiesIntoEquitySecurities',
       'InducedConversionOfConvertibleDebtExpenseExcessOfEquityConsiderationOverFairValue',
       'NoncontrollingInterestIncreaseFromDebtToEquityConversion',
       'DebtSecuritiesTradingAndEquitySecuritiesFaceAmount',
       'DebtSecuritiesTradingAndEquitySecuritiesNumberOfPositions',
       'DebtSecuritiesTradingAndEquitySecuritiesWeightedAverageCouponRate',
       'DebtAndEquitySecuritiesSoldCostBasis',
       'EarningsLossFromInvestmentInDebtAndEquityOfAffiliates',
       'InvestmentsInDebtAndEquityOfAffiliates',
       'PaymentsForProceedsFromInvestmentsInDebtAndEquityOfAffiliates',
       'DebtInstrumentCovenantTotalConsolidatedShareholdersEquityMinimumThreshold',
       'DebtInstrumentConvertibleAdditionalNumberOfEquityInstruments',
       'DebtInstrumentBookEquityRatio',
       'PaymentsToAcquireDebtAndEquitySecurities',
       'ProceedsFromSalesOfDebtAndEquitySecurities',
       'EquityMethodInvestmentDistributionThresholdWhenDebtToEquityRatioIsLessThan3.0To1.0PercentageOfNetIncome',
       'DebtInstrumentCounterpartyAmountAtRiskPercentOfStockholdersEquity',
       'DebtInstrumentCovenantAmountOfRedeemedOrRepurchasedEquity',
       'DebtInstrumentCovenantDebtToEquityRatio',
       'DebtInstrumentCovenantTangibleNetWorthAmountOfEquity',
       'RedeemableNoncontrollingInterestEquityToDebtRatio',
       'EquityPortionOfConvertibleDebt',
       'DebtSecuritiesTradingAndEquitySecuritiesFVNIMeasurementInput',
       'DebtInstrumentEquityTreatmentPercentage',
       'EquityAndDebtInvestments',
       'EquityMethodInvestmentsAndDebtSecurities',
       'RepaymentOrRetirementOfDebtEquityCancellationAndRetirementCriteria',
       'DebtInstrumentMaximumPercentageOfPrincipalAmountToBeRedeemedWithFundsNotExceedingNetCashProceedsOfEquityOfferings',
       'ProceedsFromMaturitiesPrepaymentsAndCallsOfDebtAndEquitySecurities',
       'ProceedsFromSaleOfDebtAndEquitySecurities',

In [46]:
# Define the tags you want to check
Debt_To_Equity_tags = [
    'DebtToEquityRatio',
       'DebtEquityRatio',
    'NetDebtToEquityRatio',
    'DebtInstrumentCovenantDebtToEquityRatio',
    'DebtInstrumentCovenantDebtToEquityRatioMaximum',
    'RatioOfDebtToDebtPlusEquity',
    'DebtCovenantRatioOfDebtToDebtPlusEquity',
    'TargetedMaximumDebtToEquityRatio',
    'LineofCreditFacilityCovenantTermsMaximumDebttoEquityRatio',
    'DebtInstrumentCovenantDebtToAllowanceAndEquityRatioMaximum']

# Count occurrences for each tag
for tag in Debt_To_Equity_tags:
    count = (joinedFactsAndSubmissionsAnnual['tag'] == tag).sum()
    if count > 0:
        print(f"{tag}: {count} times")
    else:
        print(f"{tag}: NOT FOUND")

DebtToEquityRatio: 3 times
DebtEquityRatio: 1 times
NetDebtToEquityRatio: 2 times
DebtInstrumentCovenantDebtToEquityRatio: 1 times
DebtInstrumentCovenantDebtToEquityRatioMaximum: 2 times
RatioOfDebtToDebtPlusEquity: 1 times
DebtCovenantRatioOfDebtToDebtPlusEquity: 1 times
TargetedMaximumDebtToEquityRatio: 1 times
LineofCreditFacilityCovenantTermsMaximumDebttoEquityRatio: 3 times
DebtInstrumentCovenantDebtToAllowanceAndEquityRatioMaximum: 1 times

In [47]:
filtered_data1 = joinedFactsAndSubmissionsAnnual[joinedFactsAndSubmissionsAnnual['tag'].isin(Debt_To_Equity_tags)]
filtered_data = pd.concat([filtered_data, filtered_data1], ignore_index=True)
filtered_data

,adsh,tag,ddate,qtrs,value,footnote,cik,name,sic,form
0,0000004281-26-000012,DebtInstrumentCovenantComplianceRatioOfConsoli...,20230731,0,3.7500,,4281,HOWMET AEROSPACE INC.,3350,10-K
1,0000004281-26-000012,DebtInstrumentCovenantComplianceRatioOfConsoli...,20251231,4,3.7500,,4281,HOWMET AEROSPACE INC.,3350,10-K
2,0000058492-26-000107,RatioOfIndebtednessToEBITDA,20251231,0,3.5000,,58492,LEGGETT & PLATT INC,2510,10-K
3,0000058492-26-000107,RatioOfIndebtednessToEBITDA,20251231,0,4.0000,,58492,LEGGETT & PLATT INC,2510,10-K
4,0000093389-26-000012,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20251231,0,1.0000,,93389,"STANDARD MOTOR PRODUCTS, INC.",3714,10-K
...,...,...,...,...,...,...,...,...,...,...
142,0001496099-26-000008,DebtInstrumentCovenantDebtToEquityRatioMaximum,20141031,0,1.6500,,1496099,NEW MOUNTAIN FINANCE CORP,,10-K
143,0001628280-26-012830,DebtToEquityRatio,20251231,0,3.0000,,1019849,"PENSKE AUTOMOTIVE GROUP, INC.",5500,10-K
144,0001630472-26-000004,DebtInstrumentCovenantDebtToEquityRatio,20251231,0,4.2500,,1630472,"TPG RE FINANCE TRUST, INC.",6798,10-K
145,0002070979-26-000018,NetDebtToEquityRatio,20241231,4,0.1978,,1066119,TELEFONICA BRASIL S.A.,4813,20-F
146,0002070979-26-000018,NetDebtToEquityRatio,20251231,4,0.1900,,1066119,TELEFONICA BRASIL S.A.,4813,20-F

In [48]:
Credit_Risk = joinedFactsAndSubmissionsAnnual[
    joinedFactsAndSubmissionsAnnual['tag'].str.contains('Credit', case=False, na=False) &
    joinedFactsAndSubmissionsAnnual['tag'].str.contains('Risk', case=False, na=False)
]
Credit_Risk['tag'].unique()

array(['ConcentrationRiskCreditRiskFinancialInstrumentMaximumExposure',
       'DerivativeCreditRiskValuationAdjustmentDerivativeAssets',
       'DerivativeCreditRiskValuationAdjustmentDerivativeLiabilities',
       'AdjustmentsToFairValueOfDerivativeContractsDueToCreditRisk',
       'LoansAndLeasesReceivableNumberOfMethodsToAssessCreditRisk',
       'FairValueInputsCreditRisk',
       'FairValueOptionCreditRiskGainsLossesOnAssets',
       'MaximumCreditRiskForRecourseAssociatedWithLoansSoldUnderFederalNationalMortgageAssociationDelegatedUnderwritingAndServicingProgram',
       'CreditRiskDerivativesPurchasedatFairValue',
       'CreditRiskDerivativesSoldatFairValue',
       'MaximumExposureUnderCreditRiskAgreementAssumingCustomerDefault',
       'CreditRiskDerivativesAtFairValueNet',
       'AggregateCreditRiskNetOfCollateral',
       'CreditRisksFromInterestRateSwapsUsedForTradingPurposes',
       'FairValueOptionCreditRiskMitigationLossReferencePoolAmount',
       'AociMarketRiskBenefitInstrumentSpecificCreditRiskBeforeTax',
       'MarketRiskBenefitAfterIncreaseDecreaseFromInstrumentSpecificCreditRisk',
       'MarketRiskBenefitAfterReinsuranceAndCumulativeIncreaseDecreaseFromInstrumentSpecificCreditRiskChange',
       'MarketRiskBenefitBeforeReinsuranceAndCumulativeIncreaseDecreaseFromInstrumentSpecificCreditRiskChange',
       'OciMarketRiskBenefitInstrumentSpecificCreditRiskGainLossAfterAdjustmentsTax',
       'DerivativeCreditRiskAndFundingValuationAdjustmentDerivative',
       'DerivativeCreditRiskAndFundingValuationAdjustmentGainLossNet',
       'CreditRiskToBanks',
       'CreditRiskToBanksNonInterestBearingBalancesHeldAtBanks',
       'CreditRiskRelatedContingentFeaturesTriggered',
       'CreditRiskDerivativeAssetsAtFairValue',
       'CreditRiskDerivativeLiabilitiesAtFairValue',
       'CreditRiskDerivativesAndGuarantorObligationsCurrentCarryingValue',
       'CreditRiskDerivativesAndGuarantorObligationsMaximumExposureUndiscounted',
       'FairValueOptionCreditRiskGainsLossesNet',
       'RiskWeightedAssetsCreditRisk',
       'MaximumExposureToCreditConcentrationRiskOfTheCompanysStockholdersEquityOtherThanCertainU.S.GovernmentAgencies',
       'AccumulatedChangesInFairValueOfFinancialAssetsAttributableToChangesInCreditRiskOfFinancialAssets',
       'AccumulatedChangesInFairValueOfFinancialLiabilityAttributableToChangesInCreditRiskOfLiability',
       'AmountByWhichFinancialAssetsRelatedCreditDerivativesOrSimilarInstrumentsMitigateMaximumExposureToCreditRisk',
       'ChangesInFairValueOfFinancialAssetsAttributableToChangesInCreditRiskOfFinancialAssets',
       'DecreaseThroughDerecognitionExposureToCreditRiskOnLoanCommitmentsAndFinancialGuaranteeContracts',
       'DecreaseThroughDisposalExposureToCreditRiskOnLoanCommitmentsAndFinancialGuaranteeContracts',
       'ExposureToCreditRiskOnLoanCommitmentsAndFinancialGuaranteeContracts',
       'IncreaseDecreaseInDrawdownsRepaymentsRiskParameterChangesAndOtherMovementsExposureToCreditRiskOnLoanCommitmentsAndFinancialGuaranteeContracts',
       'IncreaseDecreaseThroughTransfersExposureToCreditRiskOnLoanCommitmentsAndFinancialGuaranteeContracts',
       'IncreaseThroughOriginationOrPurchaseExposureToCreditRiskOnLoanCommitmentsAndFinancialGuaranteeContracts',
       'MaximumExposureToCreditRisk', 'NetExposureToCreditRisk',
       'OtherComprehensiveIncomeBeforeTaxChangeInFairValueOfFinancialLiabilityAttributableToChangeInCreditRiskOfLiability',
       'OtherComprehensiveIncomeNetOfTaxChangeInFairValueOfFinancialLiabilityAttributableToChangeInCreditRiskOfLiability',
       'TransfersExposureToCreditRisk',
       'ChangesInFairValueOfFinancialLiabilityAttributableToChangesInCreditRiskOfLiability',
       'IncreaseDecreaseInImpairmentOfFinancialInstrumentsIfSignificantIncreaseInCreditRiskHadBeenOneStepOfDeteriorationLess',
       'IncreaseDecreaseInImpairmentOfFinancialInstrumentsIfSignificantIncreaseInCreditRiskHadBeenOneStepOfDeteriorationMore',
       'CededCreditRiskReinsuranceRecoverablesNet',
       'CededCreditRiskReinsuranceRecoverablesPercentage',
       'OciMarketRiskBenefitInstrumentSpecificCreditRiskGainLossAfterAdjustmentsBeforeTax',
       'NonDerivativeCreditRiskContractAdditionalCollateralAggregateFairValue',
       'DeferredPurchaseAgreementReceivablesWithCreditRisk',
       'DerivativeCreditRiskValuationAdjustmentDerivativeAssetLiability',
       'AllowanceForCreditLossesRiskCategoriesDebtServiceCoverageRatio',
       'AllowanceForCreditLossesRiskCategoriesDebtToIncomePercentage',
       'AllowanceForCreditLossesRiskCategoriesFICOScore',
       'AllowanceForCreditLossesRiskCategoriesLoanToValuePercentage',
       'OciMarketRiskBenefitInstrumentSpecificCreditRiskGainLossAfterAdjustmentsAndTaxParent',
       'OciMarketRiskBenefitInstrumentSpecificCreditRiskGainLossBeforeAdjustmentsAndTax',
       'CounterpartyDerivativeCreditRiskValuationAdjustmentDerivativeAssets',
       'CounterpartyDerivativeCreditRiskValuationAdjustmentGainLoss',
       'DerivativeCreditRiskValuationAdjustmentGainLoss',
       'CededCreditRiskRate',
       'MaximumExposureToCreditRiskOfFinancialGuaranteeContracts',
       'DerivativeInstrumentCreditRiskExposure',
       'ConcentrationRiskCreditRiskFinancialInstrumentMaximumExposureAsPercentageOfAssets',
       'DerivativesCreditRiskGainsLossesNet',
       'MaximumExposureToCreditRiskOfFinancialAssets',
       'ExposureToCreditRiskLendingGuaranteesAndDocumentaryCredits',
       'ExposureToCreditRiskNumberOfTranches',
       'ImpactOnCreditRiskProvision',
       'IncomeTaxRelatingToChangesInFairValueOfFinancialLiabilityAttributableToChangeInCreditRiskOfLiabilityOfOtherComprehensiveIncome',
       'IncreaseDecreaseComparedToLastYearInFairValueOfFinancialLiabilityAttributableToChangesInCreditRiskOfLiability',
       'IncreaseDecreaseInCreditRiskWithCustomersPercent',
       'IncreaseDecreaseInResidentialMortgageCreditRiskPercentage',
       'LendingCreditRiskPercentageOfGroup',
       'MaximumExposureToCreditRiskOtherFinancialInstruments',
       'NumberOfCreditRiskCategories',
       'PercentageIncreaseInCreditRiskExcludingExchangeRate',
       'ReserveOfChangeInFairValueOfFinancialLiabilityAttributableToChangeInCreditRiskOfLiability',
       'AociMarketRiskBenefitInstrumentSpecificCreditRiskAfterTax',
       'OciMarketRiskBenefitInstrumentSpecificCreditRiskGainLossAfterAdjustmentsAndTax',
       'DerivativeGrossAssetFairValueWithCreditRiskContingentFeatures',
       'DerivativeGrossLiabilityFairValueWithCreditRiskContingentFeatures',
       'PotentialRecoveriesUnderCreditRiskDerivatives',
       'OtherComprehensiveIncomeLossFinancialLiabilityFairValueOptionCreditRiskArisingDuringPeriodAfterTax',
       'PercentageOfRevenueByGeographicAreaDeemedSignificantConcentrationOfCreditRisk',
       'DerivativeNetLiabilityPositionContainingCreditRiskRelatedContingencyFeatures',
       'DerivativeCreditRiskValuationAdjustmentDerivativeAssetsLiabilities',
       'FairValueDisclosureOffBalanceSheetRiskTaxCreditInvestmentCommitment',
       'CreditRiskDerivativeLiabilitiesAtFairValueExcludingHedge',
       'DerivativeCreditRiskValuationAdjustmentsDerivativeLiabilities',
       'CounterpartyCreditRiskExposurePercentageOfCreditRiskRollOff',
       'CounterpartyCreditRiskExposurePercentageThreshold',
       'EstimatedCounterpartyCreditRiskExposureToCertainCounterparties',
       'AmountByWhichCreditDerivativesOrSimilarInstrumentsRelatedToLoansOrReceivablesMitigateMaximumExposureToCreditRisk',
       'AssetsWeightedForCreditRiskEstimatedAccordingToInternalMethodologiesAWCR',
       'AssetsWeightedForCreditRiskEstimatedAccordingToTheStandardMethodologyRAW',
       'ChangesDueToChangesInCreditRisk',
       'ChangesDueToChangesUnCreditRisk',
       'MaximumExposureToCreditRiskOfLoansOrReceivables1',
       'NetChangesOfExposureAndModificationsInCreditRisk',
       'NetChangesOfTheExposureAndModificationsInCreditRisk',
       'Creditriskrelatedcontingentfeaturesdefaultondebtamount',
       'MaximumPotentialFutureExposureOnCreditRiskDerivativesWithCommodityExchangeBrokers',
       'MaximumPotentialFutureExposureOnCreditRiskDerivativesWithInvestmentGradeCounterparties',
       'CreditRiskExposureNetOfCollateralPledgedOnCreditRiskDerivatives',
       'DerivativeCreditRiskExposurePercentage',
       'ExposureToCreditRiskOffsetByCollateralHeldAsSecurity',
       'IncreaseDecreaseInAllowanceAccountForCreditLossesOnFinancialAssetsChangesToRiskParametresAndModels',
       'ExposureToCreditRiskOnReinsurersShareOfLiabilitiesUnderInsuranceContractsNeitherPastDueNorImpairedPercentage',
       'IncreaseDecreaseThroughChangesToRiskParametersCreditQualityFinancialAssets',
       'MaximumExposureToCreditRiskAmountOffset',
       'MaximumExposureToCreditRiskNetOfAmountOffset',
       'SensitivityAnalysisForTypesOfMarketRiskEffectOfOnePercentagePointDecreaseReasonablyPossibleChangeInRiskVariableEffectOnCSMShiftInCreditSpreads',
       'SensitivityAnalysisForTypesOfMarketRiskEffectOfOnePercentagePointDecreaseReasonablyPossibleChangeInRiskVariableEffectOnProfitLossAfterTaxShiftInCreditSpreads',
       'SensitivityAnalysisForTypesOfMarketRiskEffectOfOnePercentagePointDecreaseReasonablyPossibleChangeInRiskVariableEffectOnTotalEquityShiftInCreditSpreads',
       'SensitivityAnalysisForTypesOfMarketRiskEffectOfOnePercentagePointIncreaseReasonablyPossibleChangeInRiskVariableEffectOnCSMShiftInCreditSpreads',
       'SensitivityAnalysisForTypesOfMarketRiskEffectOfOnePercentagePointIncreaseReasonablyPossibleChangeInRiskVariableEffectOnProfitLossAfterTaxShiftInCreditSpreads',
       'SensitivityAnalysisForTypesOfMarketRiskEffectOfOnePercentagePointIncreaseReasonablyPossibleChangeInRiskVariableEffectOnTotalEquityShiftInCreditSpreads',
       'FinancialAssetsIncreaseDecreaseThroughChangesInModelsOrRiskParametersExpectedCreditLosses',
       'MaximumExposureToCreditRiskOffBalanceSheet',
       'AOCIMarketRiskBenefitForeignCurrencyTranslationInstrumentSpecificCreditRiskBeforeTax',
       'GainsLossesFromChangesInFairValueOfOwnDebtSecuritiesAttributableToOwnCreditRisk',
       'FairValueMeasurementWithUnobservableInputsReconciliationRecurringBasisAssetChangesInInstrumentSpecificCreditRiskIncludedInEarnings',
       'ThresholdForConcentrationOfCreditRisk',
       'NumberOfCreditRiskDerivativesHeld',
       'CreditRiskOfCommitmentsToExtendCredit',
       'CreditRiskOfLettersOfCredit',
       'CreditRiskOfUnfundedCommitmentsLinesOfCredit',
       'WeightedAverageCreditAdjustedRiskFreeInterestRate',
       'ConcentrationOfCreditRiskNumberOfFinancialInstitutions',
       'OtherComprehensiveIncomeLossCreditRiskOnFairValueDebtInstrumentsGainLossNetOfTax',
       'DerivativeCreditRiskRelatedContingentFeaturesCollateralThreshold',
       'DerivativeCreditRiskValuationAdjustmentNetDerivativeAssetsAndLiabilities',
       'TotalRiskBasedCapitalRatioAllowableReserveForCreditLossesPercentageOfRiskWeightedAssetsMaximum',
       'CreditRiskTransferPremiumExpense',
       'DebtInstrumentCreditRiskTransferPercentageOfLossOnReferencePoolOfLoans',
       'LoansCreditRiskRatingsThreshold',
       'CreditRiskAllocationPercentage',
       'IncreaseDecreaseInExposureToCreditRiskOnLoanCommitmentsAndFinancialGuaranteeContracts',
       'SensitivityAnalysisForTypesOfClimateRiskReasonablyPossibleChangeInRiskVariableImpactOnAllowanceForCreditLoss',
       'SensitivityAnalysisForTypesOfMarketRiskReasonablyPossibleChangeInRiskVariableImpactOnAllowanceForCreditLoss',
       'MitigationOfExposureToCreditRiskPercentageIncreaseDecrease',
       'CreditRiskSharingLiabilities',
       'DerivativeCreditRiskRelatedNumberOfContingentFeatures',
       'ChangeInFairValueDueToCreditRiskOnLongTermDebt',
       'GainLossOnChangeInFairValueDueToCreditRiskOnLongTermDebt',
       'LettersOfCreditOutstandingAmountForPriceRiskManagement',
       'CreditRiskMaximumExposureOfFinancialInstruments',
       'IncreaseDecreaseThroughChangesInModelsOrRiskParametersExposureToCreditRiskOnLoanCommitmentsAndFinancialGuaranteeContracts',
       'CarryingValueOfCreditRiskTransferStripsLiabilities',
       'CarryingValueOfDerivativeAndCreditRiskTransferStripLiabilities',
       'CreditRiskTransferCreditGuaranteeObligationAssets',
       'DepositsSecuringCreditRiskTransferAgreements',
       'DepositsSecuringCreditRiskTransferArrangements',
       'DepositsSecuringCreditRiskTransfersPledgedToCreditors',
       'DepositsSecuringCreditRiskTransferStripAndDerivativesLiabilities',
       'DerivativeAndCreditRiskTransferStripAssets',
       'DerivativeAndCreditRiskTransferStripAssetsPledgedToCreditors',
       'DerivativeAndCreditRiskTransferStripLiabilities',
       'DerivativeAndCreditRiskTransferStripLiabilitiesAtFairValue',
       'DistributionFromCreditRiskTransferArrangements',
       'FairValueOfCreditRiskTransferDerivatives',
       'FairValueOfCreditRiskTransferDerivativesLiabilities',
       'FairValueOptionNonCreditRiskGainsLossesOnAssets',
       'GainLossOnCreditRiskTransferArrangements',
       'GainLossOnNetDerivativeRelatesToCreditRiskTransfer',
       'GainLossRecognizedOnCreditRiskTransferStrips',
       'GainsLossesRecognizedOnCreditRiskTransferAgreements',
       'GainsLossesRecognizedOnCreditRiskTransferAgreementsIncludedInNetLossGainOnInvestments',
       'GainsLossesRecognizedOnCreditRiskTransferStripsValuationChanges',
       'InterestEarnedOnDepositsSecuringCreditRiskTransferAgreements',
       'InterestExpenseNotesPayableSecuredByCreditRiskTransferAndMortgageServicingAssets',
       'InterestIncomeOnMortgageLoansSubjectToDepositsSecuringCreditRiskTransferAgreements',
       'NotesPayableSecuredByCreditRiskTransferAndMortageServicingAsset',
       'PaymentsToCreditRiskTransferLosses',
       'RealizedGainsLossesRecognizedOnCreditRiskTransferStrips',
       'UnpaidBalanceOfLoansInReferencePoolsSubjectToCreditRiskTransferSecurities',
       'UnpaidBalanceOfMortgageLoansSubjectToCreditGuaranteeOnCreditRiskTransferAgreementsCurrent',
       'UnpaidBalanceOfMortgageLoansSubjectToCreditGuaranteeOnCreditRiskTransferAgreementsDelinquentBankruptcy',
       'UnpaidBalanceOfMortgageLoansSubjectToCreditGuaranteeOnCreditRiskTransferAgreementsDelinquentForeclosure',
       'UnpaidBalanceOfMortgageLoansUnderlyingCreditGuaranteesOnCreditRiskTransferAgreements',
       'LossContingencyReductionOfMaximumLossdueToCounterpartyCreditRiskByMasterNettingProvision',
       'ConcentrationRiskCreditRiskFinancialInstrumentMaximumExposureForSingleCounterparty',
       'ConcentrationRisksCreditRiskNumberOfCounterparties',
       'ConcentrationRiskCreditRiskFinancialInstrumentMaximumExposurePercentage',
       'ConcentrationRiskCreditRiskFinancialInstrumentMaximumExposureOnNetFairValueBasis',
       'PercentageOfReimbursementOfCollectionLossesToMitigateCreditRisks',
       'AccruedCreditLossesForFinancialInstrumentsWithOffBalanceSheetRisk',
       'CollateralCashAndSecuritiesReceivedInExchangeOfValueOfSecuritiesLentInOrderToReduceCreditRisk',
       'GainLossOnDesignationOfFinancialInstrumentAsMeasuredAtFairValueThroughProfitOrLossBecauseCreditDerivativeIsUsedToManageCreditRisk',
       'LineOfCreditRiskBasedCapitalRatio',
       'ConcentrationRiskCreditRiskFixedMaturitiesMaximumExposureCorporateIssuerAMinusOrAbovePercentageOfFixedMaturityPortfolio',
       'Concentrationriskcreditriskfixedmaturitiesmaximumexposurecorporateissuerbelowaminuspercentageoffixedmaturityportfolio',
       'AccumulatedOtherComprehensiveIncomeLossChangedInInstrumentSpecificCreditRiskForMarketRiskBenefits',
       'MarketRiskBenefitEffectOfChangesInInstrumentSpecificCreditRisk',
       'OtherComprehensiveIncomeLossAdjustmentToSpecificCreditRiskForMarketRiskBenefit',
       'FinancingReceivableAllowanceForCreditLossToRiskSharingComponentNotCoveredByTheFederalGuarantyPercent',
       'HighDeductibleClaimsCreditRiskExposureAmount',
       'CreditRiskDerivativesAtFairValueBeforeEffectOfCreditSpreadNet',
       'CapitalRiskTypeCredit',
       'CreditRiskExposureContingentLiabilitiesGuaranteesAndOtherSuretiesNote44A',
       'CreditRiskExposureCustomersThousandOfReais',
       'CreditRiskExposureLoansAndAdvancesToCustomersGrossNote9',
       'FinancialConglomeratePortionOfCreditRisk',
       'OciMarketRiskBenefitInstrumentSpecificCreditRiskGainLossAfterAdjustmentsTaxParent',
       'CashAndLettersOfCreditForSelfInsuredRetentionRisk',
       'OtherComprehensiveIncomeLossMarketRiskBenefitAfterAdjustmentFromInstrumentOfSpecialCreditRisk',
       'OffBalanceSheetCreditRisksParticipationsAmount', 'CreditRisk',
       'PrincipalcollectionsoncreditrisktransferandnonAgencysecurities',
       'ProceedsfromsaleofCreditRiskTransferandnonAgencysecurities',
       'AmountByWhichReceivablesRelatedCreditDerivativesOrSimilarInstrumentsMitigateMaximumExposureToCreditRisk',
       'MaximumExposureToCreditRiskOfReceivables',
       'FairValueOptionPercentageOfMortgageBackedSecuritiesAndGSECreditRiskTransferSecuritiesFairValue',
       'TotalCreditRiskExposureRelatedToCustomers',
       'DerivativeAssetsLiabilitiesNetFairValueOfDerivativeContractsExcludingImpactOfCreditRisk',
       'ProvisionForLoanAndLeaseLossesAndOffbalanceSheetCreditRiskExposures',
       'ConcentrationRiskCreditRiskFinancialInstrumentRetainedExposure',
       'ConcentrationRiskCreditRiskFinancialInstrumentRetainedExposureAmountDisbursed',
       'GainLossRelatedToBorrowerSpecificCreditRisk',
       'NumberOfCreditRiskParticipationAgreements',
       'CreditAdjustedRiskFreeRate',
       'CreditAdjustedRiskFreeRateSensitivityRange',
       'TheoreticalImpactToDecommissioningLiabilityFromIncreaseDecreaseCreditAdjustedRiskFreeRateSensitivity',
       'CededCreditRiskCommissionEarnedPercentage',
       'CededCreditRiskProfitCommissionEarnedPercentage',
       'ConcentrationRiskCreditRiskSubstantiallyAllCashFinancialInstitutionsNumber',
       'FairValueAssetsAndLiabilitiesMeasuredOnRecurringBasisFairValueAdjustmentInstrumentSpecificCreditRisk',
       'LoansHeldForInvestmentFairValueAdjustmentChangesInInstrumentSpecificCreditRisk',
       'MortgageLoansOnRealEstateFairValueAdjustmentCreditRiskEvaluation',
       'GainLossOnCreditRiskDerivativesNetRecognizedInEarnings',
       'ConcentrationRiskCreditRiskFinancialInstrumentsCreditExposure',
       'OffBalanceSheetLendingRelatedCommitmentsWholesaleContractualAmountNetOfRiskParticipationsOtherLettersOfCredit',
       'OffBalanceSheetLendingRelatedCommitmentsWholesaleContractualAmountNetOfRiskParticipationsOtherUnfundedCommitmentsToExtendCredit',
       'OffBalanceSheetLendingRelatedCommitmentsWholesaleContractualAmountNetOfRiskParticipationsStandbyLettersOfCreditAndOtherFinancialGuarantees',
       'ExposureToCreditRiskFromCustomers',
       'SignificantCreditRiskExposureNumberOfDistributors',
       'SignificantCreditRiskExposureRiskPercentage',
       'FairValueChangesOfFinancialLiabilitiesAtFairValueThroughProfitOrLossAttributableToChangesInTheirCreditRisk',
       'CreditDerivativePaymentPerformanceRiskPercentage',
       'ConcentrationCreditRiskAmount',
       'ConcentrationCreditRiskReceivables',
       'MaximumExposureToCreditRiskPercentage',
       'IncreaseDecreaseInInvestmentsInFinancialAssetsIncludedInCashAndCashEquivalentsExposedToCreditOrCounterpartyRisk',
       'IncreaseDecreaseInNetFinancialDerivativesAssetsExposedToCreditOrCounterpartyRisk',
       'IncreaseDecreaseInNonCurrentFinancialAssetsExposedToCreditOrCounterpartyRisk',
       'IncreaseDecreaseInTradeAndOtherReceivablesExposedToCreditOrCounterpartyRisk',
       'InvestmentsInFinancialAssetsIncludedInCashAndCashEquivalentsExposedToCreditOrCounterpartyRisk',
       'NetFinancialDerivativesAssetsExposedToCreditOrCounterpartyRisk',
       'NonCurrentFinancialAssetsExposedToCreditOrCounterpartyRisk',
       'TradeAndOtherReceivablesExposedToCreditOrCounterpartyRisk',
       'AmountByCoverInstrumentsMitigateMaximumExposureToCreditRisk',

In [49]:
# Define the tags you want to check
Credit_risk_tags = [
    'MaximumExposureToCreditRisk',
       'NetExposureToCreditRisk',
    'ConcentrationRiskCreditRiskFinancialInstrumentMaximumExposure',
    'MaximumExposureToCreditRiskOfFinancialAssets',
    'CreditRiskExposureToBankingAndFinancialSectorPercentage']

# Count occurrences for each tag
for tag in Credit_risk_tags:
    count = (joinedFactsAndSubmissionsAnnual['tag'] == tag).sum()
    if count > 0:
        print(f"{tag}: {count} times")
    else:
        print(f"{tag}: NOT FOUND")

MaximumExposureToCreditRisk: 2237 times
NetExposureToCreditRisk: 128 times
ConcentrationRiskCreditRiskFinancialInstrumentMaximumExposure: 297 times
MaximumExposureToCreditRiskOfFinancialAssets: 15 times
CreditRiskExposureToBankingAndFinancialSectorPercentage: 1 times

In [50]:
filtered_data1 = joinedFactsAndSubmissionsAnnual[joinedFactsAndSubmissionsAnnual['tag'].isin(Credit_risk_tags)]
filtered_data = pd.concat([filtered_data, filtered_data1], ignore_index=True)
filtered_data

,adsh,tag,ddate,qtrs,value,footnote,cik,name,sic,form
0,0000004281-26-000012,DebtInstrumentCovenantComplianceRatioOfConsoli...,20230731,0,3.7500,,4281,HOWMET AEROSPACE INC.,3350,10-K
1,0000004281-26-000012,DebtInstrumentCovenantComplianceRatioOfConsoli...,20251231,4,3.7500,,4281,HOWMET AEROSPACE INC.,3350,10-K
2,0000058492-26-000107,RatioOfIndebtednessToEBITDA,20251231,0,3.5000,,58492,LEGGETT & PLATT INC,2510,10-K
3,0000058492-26-000107,RatioOfIndebtednessToEBITDA,20251231,0,4.0000,,58492,LEGGETT & PLATT INC,2510,10-K
4,0000093389-26-000012,DebtInstrumentCovenantMaximumDebtToEBITDARatio,20251231,0,1.0000,,93389,"STANDARD MOTOR PRODUCTS, INC.",3714,10-K
...,...,...,...,...,...,...,...,...,...,...
2820,0001988894-26-000004,MaximumExposureToCreditRisk,20251231,0,4400000.0000,,1988894,"AMER SPORTS, INC.",2300,20-F
2821,0001988894-26-000004,MaximumExposureToCreditRisk,20251231,0,500000.0000,,1988894,"AMER SPORTS, INC.",2300,20-F
2822,0001988894-26-000004,MaximumExposureToCreditRisk,20251231,0,134300000.0000,,1988894,"AMER SPORTS, INC.",2300,20-F
2823,0001988894-26-000004,MaximumExposureToCreditRisk,20251231,0,22300000.0000,,1988894,"AMER SPORTS, INC.",2300,20-F
2824,0001988894-26-000004,MaximumExposureToCreditRisk,20251231,0,652300000.0000,,1988894,"AMER SPORTS, INC.",2300,20-F

In [51]:
filtered_data1.to_csv('filtered_data.csv', index=False)

In [52]:
Risk_factor = joinedTextAndSubmissionsAnnual[
    joinedTextAndSubmissionsAnnual['tag'].str.contains('Factor', case=False, na=False) &
    joinedTextAndSubmissionsAnnual['tag'].str.contains('Risk', case=False, na=False)
]
Risk_factor['tag'].unique()

array(['SchedulesOfConcentrationOfRiskByRiskFactorTextBlock',
       'SchedulesOfConcentrationOfRiskByRiskFactorRelatedToCollaborativePartnersTableTextBlock',
       'DisclosureOfNatureAndExtentOfRisksByRiskFactorTextBlock',
       'DescriptionOfFinancialRiskFactorsAndRiskManagementPolicyTextBlock',
       'RiskFactorsTableTextBlock', 'VaRByRiskFactorTableTextBlock'],
      dtype=object)

In [53]:
# Define the tags you want to check
Risk_factor_tags = ['SchedulesOfConcentrationOfRiskByRiskFactorTextBlock',
       'SchedulesOfConcentrationOfRiskByRiskFactorRelatedToCollaborativePartnersTableTextBlock',
       'DisclosureOfNatureAndExtentOfRisksByRiskFactorTextBlock',
       'DescriptionOfFinancialRiskFactorsAndRiskManagementPolicyTextBlock',
       'RiskFactorsTableTextBlock', 'VaRByRiskFactorTableTextBlock']

# Count occurrences for each tag
for tag in Risk_factor_tags:
    count = (joinedTextAndSubmissionsAnnual['tag'] == tag).sum()
    if count > 0:
        print(f"{tag}: {count} times")
    else:
        print(f"{tag}: NOT FOUND")

SchedulesOfConcentrationOfRiskByRiskFactorTextBlock: 222 times
SchedulesOfConcentrationOfRiskByRiskFactorRelatedToCollaborativePartnersTableTextBlock: 1 times
DisclosureOfNatureAndExtentOfRisksByRiskFactorTextBlock: 1 times
DescriptionOfFinancialRiskFactorsAndRiskManagementPolicyTextBlock: 1 times
RiskFactorsTableTextBlock: 131 times
VaRByRiskFactorTableTextBlock: 1 times

In [54]:
filtered_data1 = joinedTextAndSubmissionsAnnual[joinedTextAndSubmissionsAnnual['tag'].isin(Risk_factor_tags)]
filtered_data1

,adsh,tag,version,ddate,qtrs,footnote,value,cik,name,sic,form
1825,0000004904-26-000013,SchedulesOfConcentrationOfRiskByRiskFactorText...,us-gaap/2025,20251231,4,,AEP Texas had significant customers which acco...,4904,AMERICAN ELECTRIC POWER CO INC,4911,10-K
31853,0000073124-26-000016,SchedulesOfConcentrationOfRiskByRiskFactorText...,us-gaap/2025,20251231,4,,The table below provides additional detail reg...,73124,NORTHERN TRUST CORP,6022,10-K
33019,0000076605-26-000013,SchedulesOfConcentrationOfRiskByRiskFactorText...,us-gaap/2025,20251231,4,,The Company had two major customers that accou...,76605,PATRICK INDUSTRIES INC,3714,10-K
34064,0000078003-26-000026,SchedulesOfConcentrationOfRiskByRiskFactorText...,us-gaap/2025,20251231,4,,"The following summarizes revenue, as a percent...",78003,PFIZER INC,2834,10-K
36316,0000085535-26-000008,SchedulesOfConcentrationOfRiskByRiskFactorText...,us-gaap/2025,20251231,4,,Operators that contributed greater than 10% of...,85535,ROYAL GOLD INC,6795,10-K
...,...,...,...,...,...,...,...,...,...,...,...
672238,0001880319-26-000013,SchedulesOfConcentrationOfRiskByRiskFactorText...,us-gaap/2025,20251231,4,,Net sales by geographical area are as follows:...,1880319,"PERIMETER SOLUTIONS, INC.",2800,10-K
673835,0001895262-26-000076,SchedulesOfConcentrationOfRiskByRiskFactorText...,us-gaap/2025,20251231,4,,The following table sets forth revenues from o...,1895262,NOBLE CORP PLC,1381,10-K
675234,0001907982-26-000026,SchedulesOfConcentrationOfRiskByRiskFactorText...,us-gaap/2025,20251231,4,,The tables below present the significant custo...,1907982,D-WAVE QUANTUM INC.,7374,10-K
677107,0001934850-26-000026,SchedulesOfConcentrationOfRiskByRiskFactorText...,us-gaap/2025,20251231,4,,Our underlying investment concentrations that ...,1934850,"F&G ANNUITIES & LIFE, INC.",6311,10-K
680415,0001981599-26-000020,SchedulesOfConcentrationOfRiskByRiskFactorText...,us-gaap/2025,20251231,4,,The following table represents the Companys re...,1981599,"CENTURI HOLDINGS, INC.",4923,10-K

In [55]:
Credit_Risk = joinedTextAndSubmissionsAnnual[
    joinedTextAndSubmissionsAnnual['tag'].str.contains('Credit', case=False, na=False) &
    joinedTextAndSubmissionsAnnual['tag'].str.contains('Risk', case=False, na=False)
]
Credit_Risk['tag'].unique()

array(['ConcentrationRiskCreditRisk',
       'ConcentrationRiskCreditRiskFinancialInstrumentsTableTextBlock',
       'ScheduleOfCededCreditRiskByReinsurerTextBlock',
       'ConcentrationRiskCreditRiskPolicyAndOffBalanceSheetCreditExposurePolicyPolicyTextBlock',
       'CreditRiskAssociatedWithCommitmentsTableTextBlock',
       'CreditRiskAssociatedWithLettersOfCreditTableTextBlock',
       'NotionalAndCreditRiskAmountsOfOutstandingDerivativePositionsTableTextBlock',
       'ConcentrationOfCreditRisksExposuresAndFinancialInstrumentsPolicyPolicyTextBlock',
       'ScheduleofDerivativeContractsCreditRiskContingentFeaturesTableTextBlock',
       'AverageTermOfCreditRiskDerivatives1',
       'CreditRiskRelatedContingentFeaturesTableTextBlock',
       'SummaryOfCreditRatingsOfCreditRiskRelatedGuaranteesTableTableTextBlock',
       'DerivativesCreditRiskRiskParticipationAgreementsTableTextBlock',
       'DisclosureOfAnalysisOfCreditRiskProfileContingentLiabilitiesAndLoanCommitmentsTextBlock',
       'DisclosureOfCreditQualityOfAssetsExposedToCreditRiskTextBlock',
       'DisclosureOfCreditRiskExplanatory',
       'DisclosureOfCreditRiskExposureExplanatory',
       'ExplanationOfCreditRiskManagementPracticesAndHowTheyRelateToRecognitionAndMeasurementOfExpectedCreditLossesExplanatory',
       'DisclosureOfCreditRiskByProbabilityOfDefaultGradeTableTextBlock',
       'DisclosureOfEffectOfCreditRiskMitigationTableTextBlock',
       'FinancingReceivableAllowanceForCreditLossCommonRiskCharacteristicsForecastPeriod',
       'FinancingReceivableAllowanceForCreditLossCommonRiskCharacteristicsHistoricalLossExperiencePeriod',
       'ScheduleOfDerivativeCreditRiskRelatedContingentFeaturesTableTextBlock',
       'ScheduleOfPotentialCollateralRequirementsForDerivativeLiabilitiesWithCreditRiskContingentFeaturesTableTextBlock',
       'ScheduleOfOffBalanceSheetFinancialInstrumentsWithCreditRiskTableTextBlock',
       'ConcentrationOfCreditRiskPolicyTextBlock',
       'AverageTermofCreditRiskDerivativesLessthan1Year',
       'ConcentrationsOfCreditRiskPolicyTextBlock',
       'ConcentrationRiskCreditRiskLoanProducts',
       'FinancialInstrumentsAndConcentrationsOfCreditRiskTextBlock',
       'ConcentrationOfCreditRiskPolicyPolicyTextBlock',
       'EstimatedCounterpartyCreditRiskExposureToCertainCounterpartiesPeriod',
       'DisclosureOfDetailedInformationCreditRiskExposureExplanatoryTableTextBlock',
       'AccountsReceivableAndCreditRiskPolicyTextBlock',
       'FinancingReceivableCreditQualityIndicatorsKeyCreditRiskCharacteristicsAndMacroeconomicVariablesTableTextBlock',
       'ConcentrationsOfCreditRiskProductsRevenuesAndCustomersPolicyTextBlock',
       'ScheduleOfCreditRiskRelatedContingentFeaturesTableTextBlock',
       'MarketRiskBenefitAfterIncreaseDecreaseFromInstrumentSpecificCreditRiskTableTextBlock',
       'CreditRiskPolicyPolicyTextBlock',
       'CreditRiskCommitmentsExpirationDate',
       'ConcentrationRiskCreditRiskAndTradeReceivablesPolicyTextBlock',
       'ScheduleOfFinancingReceivableCreditQualityIndicatorsBasedOnInternallyAssignedRiskRatingTableTextBlock',
       'CreditRiskProfileOfResidentialRealEstateAndConsumerLoanPortfolioBasedOnPerformingAndNonperformingStatusSegregatedByClassTableTextBlock',
       'DisclosureOfDetailedInformationAboutSignificantIncreaseInCreditRiskExplanatoryTableTextBlock',
       'CreditRiskAndReserveForLossesOnReceivablesPolicyPolicyPolicyTextBlock',
       'ConcentrationsOfCreditRiskAndOfBalanceSheetRiskPolicyTextBlockPolicyTextBlock',
       'DisclosureDetailsOfMaximumCreditRiskExposureBeforeCollateralReceivedTableTextBlock',
       'DerivativeAndCreditRiskTransferStripAssetsAndLiabilitiesPolicyTextBlock',
       'ScheduleOfCreditRiskTransferAgreementsTableTextBlock',
       'ScheduleOfKeyUnobservableInputsUsedInValuationOfCreditRiskTransfersTableTextBlock',
       'ScheduleOfKeyUnobservableInputsUsedInValuationOfInterestOnlyStrippedCreditRiskTransferSecuritiesAtFairValueTableTextBlock',
       'ScheduleOfSecuredNotePayableOfCreditRiskTransferAndMortgageServicingRightsTableTextBlock',
       'ConcentrationOfCreditRiskCreditLossesAndOtherRisksAndUncertaintiesPolicyTextBlock',
       'ConcentrationOfCreditRiskAndAccountsReceivablePolicyTextBlock',
       'ConcentrationRiskCreditRiskFinancialInstrumentsOffBalanceSheetRisk',
       'OffBalanceSheetRiskAndConcentrationsOfCreditRiskPolicyPolicyTextBlock',
       'ConcentrationRiskCreditRiskFinancialInstruments',
       'ConcentrationOfCreditRiskAndOtherRisksAndUncertaintiesPolicyTextBlock',
       'MaturityOfCreditRiskDerivative',
       'ConcentrationOfCreditRiskAndAllowanceForCreditLossesPolicyPolicyTextBlock',
       'ConcentrationOfCreditRiskAndOfSignificantSuppliersPolicyTextBlock',
       'OffBalanceSheetRiskAndConcentrationOfCreditRiskPolicyTextBlock',
       'CreditRiskAndAllowanceForDoubtfulAccountsPolicyTextBlock',
       'ConcentrationsOfCreditRiskAndOffBalanceSheetRiskPolicyTextBlock',
       'ConcentrationOfCreditRiskAndOtherRisksAndUncertaintiesPolicyPolicyTextBlock',
       'ConcentrationOfCreditRiskAndSignificantSuppliersPolicyTextBlock',
       'ConcentrationOfCreditRiskAndSignificantCustomersPolicyTextBlock',
       'CommitmentsContingenciesConcentrationOfCreditRiskAndOffBalanceSheetRiskDisclosureTextBlock',
       'DescriptionOfCreditRiskExposure', 'CreditRiskPolicyTextBlock',
       'CreditRiskAssociatedwithoffbalancesheetarrangementsTableTableTextBlock',
       'ConcentrationOfCreditRiskInFinancialInstrumentsPolicyTextBlock',
       'ConcentrationsOfCreditAndOtherRisksAndUncertaintiesPolicyTextBlock',
       'ConcentrationsOfCreditRiskTableTableTextBlock',
       'FinancialInstrumentsAndConcentrationOfCreditRiskPolicyPolicyTextBlock',
       'CreditRiskAndInterestRateRiskDisclosureTextBlock',
       'MaximumTermOfCreditRiskDerivatives1',
       'CreditRiskContractualPaymentsMinimumPeriod',
       'CreditRiskAndFairValueOfFinancialInstrumentsTextBlock',
       'CreditRiskAdjustmentsOnDerivativeAssetsAndLiabilitiesAndDebtInstrumentsGainsLossesTextBlockTableTextBlock',
       'CreditRiskConcentrationsTableTextBlock',
       'DisclosureOfCurrentCreditAndLiquidityRiskOfDerivativesTableTextBlock',
       'AllowanceForDoubtfulAccountsAndConcentrationOfCreditRiskPolicyPolicyTextBlock',
       'DetailsOfTreasuryAndOtherFinancialRisksCreditRiskWithNumberOfCounterpartiesTableTextBlock',
       'MaximumCreditRiskExposureAccumulatedAllowancesAndCarryingAmountByCounterpartyTableTextBlock',
       'MaximumCreditRiskExposureAccumulatedAllowancesAndCarryingAmountByGeographicalLocationTableTextBlock',
       'MaximumCreditRiskExposureTableTextBlock',
       'CreditRiskContingentFeatureTableTextBlock',
       'ConcentrationsOfCreditAndBusinessRiskPolicyTextBlock',
       'ConcentrationRiskCreditRiskFinancialInstrumentsOffBalanceSheetRiskTextBlock',
       'ConcentrationOfCreditRiskCreditLossAndOtherRisksAndUncertaintiesPolicyTextBlock',
       'DisclosureOfDetailedInformationAboutTheGroupMainFinancialAssetsExposedToCreditOrCounterPartyRiskTableTextBlock',
       'CreditSpreadSensitivitiesPerRiskClassAndSectorExplanatoryTableTextBlock',
       'DisclosureOfCreditRiskExposureByLineOfBusinessTableTextBlock',
       'DisclosureOfCreditRiskExposurePerEconomicSectorTableTextBlock',
       'SensitivityAnalysisForCreditRisk',
       'CommitmentsContingenciesAndConcentrationsOfCreditRiskDisclosureTextBlock',
       'ConcentrationRiskCreditRiskPolicyTextBlock',
       'CreditAndMarketRiskManagementPolicyTextBlock',
       'CreditRiskRelatedContingentFeaturesOfDerivativesTableTextBlock',
       'ConcentrationOfCreditRiskOtherRisksAndUncertaintiesPolicyTextBlock',
       'FairValueofDerivativeswithCreditRiskRelatedContingentFeaturesTableTextBlockTableTextBlock',
       'DisclosureOfDetailedInformationAboutMaximumAmountOfCreditRiskAtReportingDatesExplanatoryTableTextBlock'],
      dtype=object)

In [56]:
# Define the tags you want to check
Risk_factor_tags = ['ConcentrationRiskCreditRisk']

# Count occurrences for each tag
for tag in Risk_factor_tags:
    count = (joinedTextAndSubmissionsAnnual['tag'] == tag).sum()
    if count > 0:
        print(f"{tag}: {count} times")
    else:
        print(f"{tag}: NOT FOUND")

ConcentrationRiskCreditRisk: 716 times

In [57]:
# Get the first matching row
first_match = joinedTextAndSubmissionsAnnual[joinedTextAndSubmissionsAnnual['tag'] == 'ConcentrationRiskCreditRisk'].iloc[0]

# Then access a column, for example 'value'
value = first_match['value']
print(value)

Concentration of Credit Risk Financial instruments that potentially subject us to a concentration of counterparty credit risk, or the risk that a counterparty will be unable to meet its commitments, consist principally of accounts receivable and contract assets related to our long-term SPAs, as our contracted LNG sales are primarily under SPAs with terms exceeding 10 years. As of December 31, 2025, we had SPAs with initial terms of 10 or more years with approximately 30 different third party customers, with customers under common control being considered a single customer. We are dependent on the respective customers creditworthiness and their ability to perform under their respective agreements. While substantially all of our long-term third party customer arrangements are executed with a creditworthy company or secured by a parent company guarantee or other form of collateral, we are nonetheless exposed to credit risk in the event of a customer default that requires us to seek recourse. Additionally, we maintain cash balances at financial institutions, which may at times be in excess of federally insured levels. We have not incurred credit losses related to these cash balances to date. While we use derivative instruments that expose us to counterparty credit risk, our underlying arrangements typically include provisions that protect us and our counterparties against such risk. For example, our commodity derivatives executed over-the-counter or through an exchange often require collateral that is returned to us (or to the counterparty) on or near the settlement date or are settled on a daily margin basis with investment grade financial institutions, and are primarily facilitated by independent system operators and by clearing brokers. For non-exchange traded transactions, payments on margin deposits, either by us or by the counterparty depending on the position, are required when the value of a derivative exceeds the pre-established credit limit with the counterparty. Our FX derivative instruments are placed with investment grade financial institutions whom we believe have insignificant credit risks. We monitor counterparty creditworthiness on an ongoing basis; however, we cannot predict sudden changes in counterparties creditworthiness. Even if such changes are not sudden, we may be limited in our ability to mitigate an increase in counterparty credit risk. Should one of these counterparties not perform, we may not realize the benefit of some of our assets.

In [63]:
credit_tags = set(Credit_Risk['tag'].unique())
final_tags = set(filtered_data['tag'].unique())
common_tags = credit_tags.intersection(final_tags)

print(f"Number of matching tags: {len(common_tags)}")
print(common_tags)

Number of matching tags: 0
set()

In [64]:
# Define the tags you want to check
Risk_credit_tags = ['ConcentrationRiskCreditRisk',
                    'ConcentrationRiskCreditRiskFinancialInstruments', 
                    'ConcentrationOfCreditRiskPolicyTextBlock',
                   'CreditRiskPolicyPolicyTextBlock',
                    'CreditRiskPolicyTextBlock'
                    , 'CreditRiskAndAllowanceForDoubtfulAccountsPolicyTextBlock',
"DisclosureOfCreditRiskExplanatory", "DisclosureOfCreditRiskExposureExplanatory", "ConcentrationOfCreditRiskPolicyTextBlock", "DisclosureOfCreditQualityOfAssetsExposedToCreditRiskTextBlock", "CreditRiskRelatedContingentFeaturesTableTextBlock", "MaximumCreditRiskExposureTableTextBlock", "DisclosureOfEffectOfCreditRiskMitigationTableTextBlock", "AccountsReceivableAndCreditRiskPolicyTextBlock", "OffBalanceSheetRiskAndConcentrationOfCreditRiskPolicyTextBlock"]

# Count occurrences for each tag
for tag in Risk_credit_tags:
    count = (joinedTextAndSubmissionsAnnual['tag'] == tag).sum()
    if count > 0:
        print(f"{tag}: {count} times")
    else:
        print(f"{tag}: NOT FOUND")

ConcentrationRiskCreditRisk: 716 times
ConcentrationRiskCreditRiskFinancialInstruments: 1 times
ConcentrationOfCreditRiskPolicyTextBlock: 9 times
CreditRiskPolicyPolicyTextBlock: 1 times
CreditRiskPolicyTextBlock: 1 times
CreditRiskAndAllowanceForDoubtfulAccountsPolicyTextBlock: 1 times
DisclosureOfCreditRiskExplanatory: 15 times
DisclosureOfCreditRiskExposureExplanatory: 20 times
ConcentrationOfCreditRiskPolicyTextBlock: 9 times
DisclosureOfCreditQualityOfAssetsExposedToCreditRiskTextBlock: 2 times
CreditRiskRelatedContingentFeaturesTableTextBlock: 1 times
MaximumCreditRiskExposureTableTextBlock: 1 times
DisclosureOfEffectOfCreditRiskMitigationTableTextBlock: 1 times
AccountsReceivableAndCreditRiskPolicyTextBlock: 1 times
OffBalanceSheetRiskAndConcentrationOfCreditRiskPolicyTextBlock: 1 times

In [66]:
filtered_data2 = joinedTextAndSubmissionsAnnual[joinedTextAndSubmissionsAnnual['tag'].isin(Risk_credit_tags)]
filtered_data1= pd.concat([filtered_data1, filtered_data2], ignore_index=True)
filtered_data1

,adsh,tag,version,ddate,qtrs,footnote,value,cik,name,sic,form
0,0000004904-26-000013,SchedulesOfConcentrationOfRiskByRiskFactorText...,us-gaap/2025,20251231,4,,AEP Texas had significant customers which acco...,4904,AMERICAN ELECTRIC POWER CO INC,4911,10-K
1,0000073124-26-000016,SchedulesOfConcentrationOfRiskByRiskFactorText...,us-gaap/2025,20251231,4,,The table below provides additional detail reg...,73124,NORTHERN TRUST CORP,6022,10-K
2,0000076605-26-000013,SchedulesOfConcentrationOfRiskByRiskFactorText...,us-gaap/2025,20251231,4,,The Company had two major customers that accou...,76605,PATRICK INDUSTRIES INC,3714,10-K
3,0000078003-26-000026,SchedulesOfConcentrationOfRiskByRiskFactorText...,us-gaap/2025,20251231,4,,"The following summarizes revenue, as a percent...",78003,PFIZER INC,2834,10-K
4,0000085535-26-000008,SchedulesOfConcentrationOfRiskByRiskFactorText...,us-gaap/2025,20251231,4,,Operators that contributed greater than 10% of...,85535,ROYAL GOLD INC,6795,10-K
...,...,...,...,...,...,...,...,...,...,...,...
1123,0002013745-26-000007,ConcentrationRiskCreditRisk,us-gaap/2024,20251231,4,,Concentrations of Credit Risk The Company perf...,2013745,"CALUMET, INC. /DE",2911,10-K
1124,0002038564-26-000004,ConcentrationRiskCreditRisk,us-gaap/2025,20251130,4,,Concentration of Credit Risk Financial instrum...,2038564,ALPHEGA INNOVATIONS CORP,7374,10-K
1125,0002046386-26-000009,ConcentrationRiskCreditRisk,us-gaap/2025,20251231,4,,Concentrations of Credit Risk The Company dive...,2046386,MEDLINE INC.,3841,10-K
1126,0002067129-26-000007,ConcentrationRiskCreditRisk,us-gaap/2025,20251231,4,,Concentrations of Credit Risk: Financial instr...,2067129,NEPTUNE INSURANCE HOLDINGS INC.,6411,10-K
1127,0002074176-26-000010,ConcentrationRiskCreditRisk,us-gaap/2025,20251231,4,,Concentrations The Company is subject to risk ...,2074176,"VIPER ENERGY, INC.",1311,10-K

In [68]:
Liquidity_Risk = joinedTextAndSubmissionsAnnual[
    joinedTextAndSubmissionsAnnual['tag'].str.contains('Liquidity', case=False, na=False) &
    joinedTextAndSubmissionsAnnual['tag'].str.contains('Risk', case=False, na=False)
]
Liquidity_Risk['tag'].unique()

array(['DisclosureOfMaturityAnalysisForFinancialAssetsHeldForManagingLiquidityRiskExplanatory',
       'DisclosureOfLiquidityRiskExplanatory',
       'ScheduleOfKeyFiguresForLiquidityRiskTableTextBlock',
       'DescriptionOfManagingLiquidityRisk',
       'DisclosureOfMaturityAnalysisForLiquidityRiskThatArisesFromContractsWithinScopeOfIFRS17Explanatory',
       'RisksAndLiquidityTextBlock', 'LiquidityRiskPolicyTextBlock',
       'DisclosureOfCurrentCreditAndLiquidityRiskOfDerivativesTableTextBlock',
       'RisksAndUncertaintiesAndLiquidityPolicyTextBlock',
       'RiskAndLiquidityDisclosureTextBlock'], dtype=object)

In [69]:
# Define the tags you want to check
Liquidity_Risk_tags = ['DisclosureOfMaturityAnalysisForFinancialAssetsHeldForManagingLiquidityRiskExplanatory',
       'DisclosureOfLiquidityRiskExplanatory',
       'ScheduleOfKeyFiguresForLiquidityRiskTableTextBlock',
       'DescriptionOfManagingLiquidityRisk',
       'DisclosureOfMaturityAnalysisForLiquidityRiskThatArisesFromContractsWithinScopeOfIFRS17Explanatory',
       'RisksAndLiquidityTextBlock', 'LiquidityRiskPolicyTextBlock',
       'DisclosureOfCurrentCreditAndLiquidityRiskOfDerivativesTableTextBlock',
       'RisksAndUncertaintiesAndLiquidityPolicyTextBlock',
       'RiskAndLiquidityDisclosureTextBlock']

# Count occurrences for each tag
for tag in Liquidity_Risk_tags:
    count = (joinedTextAndSubmissionsAnnual['tag'] == tag).sum()
    if count > 0:
        print(f"{tag}: {count} times")
    else:
        print(f"{tag}: NOT FOUND")

DisclosureOfMaturityAnalysisForFinancialAssetsHeldForManagingLiquidityRiskExplanatory: 3 times
DisclosureOfLiquidityRiskExplanatory: 8 times
ScheduleOfKeyFiguresForLiquidityRiskTableTextBlock: 1 times
DescriptionOfManagingLiquidityRisk: 4 times
DisclosureOfMaturityAnalysisForLiquidityRiskThatArisesFromContractsWithinScopeOfIFRS17Explanatory: 4 times
RisksAndLiquidityTextBlock: 1 times
LiquidityRiskPolicyTextBlock: 1 times
DisclosureOfCurrentCreditAndLiquidityRiskOfDerivativesTableTextBlock: 1 times
RisksAndUncertaintiesAndLiquidityPolicyTextBlock: 1 times
RiskAndLiquidityDisclosureTextBlock: 1 times

In [70]:
filtered_data2 = joinedTextAndSubmissionsAnnual[joinedTextAndSubmissionsAnnual['tag'].isin(Liquidity_Risk_tags)]
filtered_data1= pd.concat([filtered_data1, filtered_data2], ignore_index=True)
filtered_data1

,adsh,tag,version,ddate,qtrs,footnote,value,cik,name,sic,form
0,0000004904-26-000013,SchedulesOfConcentrationOfRiskByRiskFactorText...,us-gaap/2025,20251231,4,,AEP Texas had significant customers which acco...,4904,AMERICAN ELECTRIC POWER CO INC,4911,10-K
1,0000073124-26-000016,SchedulesOfConcentrationOfRiskByRiskFactorText...,us-gaap/2025,20251231,4,,The table below provides additional detail reg...,73124,NORTHERN TRUST CORP,6022,10-K
2,0000076605-26-000013,SchedulesOfConcentrationOfRiskByRiskFactorText...,us-gaap/2025,20251231,4,,The Company had two major customers that accou...,76605,PATRICK INDUSTRIES INC,3714,10-K
3,0000078003-26-000026,SchedulesOfConcentrationOfRiskByRiskFactorText...,us-gaap/2025,20251231,4,,"The following summarizes revenue, as a percent...",78003,PFIZER INC,2834,10-K
4,0000085535-26-000008,SchedulesOfConcentrationOfRiskByRiskFactorText...,us-gaap/2025,20251231,4,,Operators that contributed greater than 10% of...,85535,ROYAL GOLD INC,6795,10-K
...,...,...,...,...,...,...,...,...,...,...,...
1148,0001628280-26-006874,DisclosureOfLiquidityRiskExplanatory,ifrs/2025,20251231,4,,The Groups policy is to have a strong liquidit...,1639920,SPOTIFY TECHNOLOGY S.A.,4832,20-F
1149,0001628280-26-008131,DisclosureOfCurrentCreditAndLiquidityRiskOfDer...,0001628280-26-008131,20251231,4,,The following table shows the aggregate fair v...,19617,JPMORGAN CHASE & CO,6021,10-K
1150,0001628280-26-009886,RisksAndUncertaintiesAndLiquidityPolicyTextBlock,0001628280-26-009886,20251231,4,,Risks and uncertainties and liquidity As a min...,1853962,I-80 GOLD CORP.,1040,10-K
1151,0001628280-26-010858,DisclosureOfLiquidityRiskExplanatory,ifrs/2025,20251231,4,,Liquidity risk management Liquidity risk arise...,844551,WOODSIDE ENERGY GROUP LTD,1311,20-F
1152,0001821586-26-000002,RiskAndLiquidityDisclosureTextBlock,0001821586-26-000002,20251231,4,,"Risks and Liquidity Going Concern, Liquidity a...",1821586,MOONLAKE IMMUNOTHERAPEUTICS,2834,10-K

In [71]:
filtered_data1.to_csv('text_filtered_data.csv', index=False)